import type { HomeAssistant } from "./types";

const translations: Record<string, Record<string, string>> = {
  en: {
    entity: "Entity", name: "Custom name", name_mode: "Name", secondary: "Custom secondary information", icon: "Icon",
    icon_color: "Icon color", variant: "Card style", layout: "Layout",
    icon_type: "Icon type", fill_container: "Fill container",
    primary_info: "Primary information", secondary_info: "Secondary information",
    show_icon: "Show icon", show_state: "Show state", tap_action: "Tap action",
    hold_action: "Hold action", double_tap_action: "Double-tap action",
    collapse_entity: "Collapse helper", collapsed: "Show collapsed",
    temperature_entity: "Temperature sensor", humidity_entity: "Humidity sensor",
    battery_entity: "Battery sensor", graph_entity: "Graph sensor", eta_entity: "ETA sensor",
    disk_entity: "Disk usage sensor", memory_entity: "Memory usage sensor", cpu_entity: "CPU usage sensor",
    disk_name: "Disk label", disk_icon: "Disk icon", disk_color: "Disk color",
    temperature_name: "Temperature label", temperature_icon: "Temperature icon", temperature_color: "Temperature color",
    temperature_max: "Temperature chart maximum",
    memory_name: "Memory label", memory_icon: "Memory icon", memory_color: "Memory color",
    memory_max: "Memory chart maximum",
    cpu_name: "CPU label", cpu_icon: "CPU icon", cpu_color: "CPU color", cpu_max: "CPU chart maximum",
    graph_span: "History range", chart_type: "Chart style",
    address_entity: "Address sensor", min_entity: "Minimum sensor", max_entity: "Maximum sensor",
    show_today: "Show today's collection summary", today_entity: "Today's collection summary sensor",
    show_tomorrow: "Show tomorrow's collection summary", tomorrow_entity: "Tomorrow's collection summary sensor",
    show_forecast: "Show forecast", show_controls: "Show controls", show_graph: "Show graph",
    use_entity_picture: "Use entity picture", graph_hours: "Graph hours", console_platform: "Console platform",
    ulm_card_weather_backdrop: "Show weather background",
    ulm_card_weather_primary_info: "Main weather information",
    ulm_card_weather_secondary_info: "Additional weather information",
    ulm_card_light_enable_slider: "Show brightness slider",
    ulm_card_light_enable_slider_minSet: "Minimum slider brightness",
    ulm_card_light_enable_slider_maxSet: "Maximum slider brightness",
    ulm_card_light_enable_collapse: "Collapse controls when light is off",
    ulm_card_light_enable_horizontal: "Use horizontal layout",
    ulm_card_light_enable_color: "Use the light's current color",
    ulm_card_light_force_background_color: "Color the card when light is on",
    ulm_card_light_enable_buttons: "Show brightness preset buttons",
    ulm_card_light_brightness_low: "Low brightness preset",
    ulm_card_light_brightness_medium: "Medium brightness preset",
    ulm_card_light_brightness_high: "High brightness preset",
    ulm_card_battery_battery_level_danger: "Low battery threshold",
    ulm_card_battery_battery_level_warning: "Battery warning threshold",
    ulm_card_battery_charging_animation: "Animate while charging",
    ulm_card_media_player_enable_art: "Show media artwork",
    ulm_card_media_player_enable_controls: "Show playback controls",
    ulm_card_media_player_enable_volume_slider: "Show volume slider",
    ulm_card_cover_enable_slider: "Show position slider",
    ulm_card_cover_slider_min: "Minimum cover position",
    ulm_card_cover_slider_max: "Maximum cover position",
    ulm_card_fan_enable_slider: "Show speed slider",
    ulm_card_fan_slider_min: "Minimum fan speed",
    ulm_card_fan_slider_max: "Maximum fan speed",
    ulm_card_fan_enable_button: "Show oscillation button",
    ulm_card_fan_button_icon: "Oscillation button icon",
    ulm_card_binary_sensor_show_last_changed: "Show when the state last changed",
    ulm_card_binary_sensor_alert_show_last_changed: "Show when the alert last changed",
    ulm_custom_card_bar_card_color: "Bar color",
    ulm_custom_card_bar_card_icon: "Header icon",
    ulm_custom_card_bar_card_icon_color: "Icon color",
    ulm_custom_card_bar_card_indicator: "Show bar indicator",
    ulm_custom_card_bar_card_max: "Maximum value",
    ulm_custom_card_bar_card_min: "Minimum value",
    ulm_custom_card_bar_card_name: "Header name",
    ulm_custom_card_bar_card_show_icon: "Show icon and header",
    ulm_custom_card_bar_card_value: "Show value inside bar",
    ulm_custom_card_washer_power: "Power sensor",
    ulm_card_homeassistant_entity: "Overall updates entity",
    ulm_card_homeassistant_core: "Home Assistant Core update entity",
    ulm_card_homeassistant_supervisor: "Supervisor update entity",
    ulm_card_homeassistant_os: "Home Assistant OS update entity",
    tablet_button_usb_entity: "USB control",
    tablet_button_motion_entity: "Motion control",
    tablet_button_display_entity: "Display control",
    tablet_restart_entity: "Restart button",
    tablet_maintenance_entity: "Maintenance mode control",
    tablet_reload_entity: "Reload button",
    tablet_ram_entity: "RAM usage sensor",
    tablet_disk_entity: "Disk usage sensor",
    tablet_power_entity: "Power state entity",
    ulm_card_person_entity: "Person",
    ulm_card_person_use_entity_picture: "Use person picture",
    ulm_card_person_zone1: "First known zone",
    ulm_card_person_zone2: "Second known zone",
    ulm_address: "Address sensor",
    ulm_address_locality: "Address locality sensor",
    ulm_card_person_driving_entity: "Driving status sensor",
    ulm_card_person_battery_entity: "Battery level sensor",
    ulm_card_person_battery_state_entity: "Battery charging-state sensor",
    ulm_card_person_commute_entity: "Commute time sensor",
    ulm_card_person_cummute_icon: "Commute icon",
    ulm_multiline: "Use multiline layout",
  },
  de: {
    entity: "Entität", name: "Name", secondary: "Sekundärinformation", icon: "Symbol",
    icon_color: "Symbolfarbe", variant: "Variante", layout: "Layout",
    show_icon: "Symbol anzeigen", show_state: "Status anzeigen", tap_action: "Tippaktion",
    hold_action: "Halteaktion", double_tap_action: "Doppeltippaktion",
    temperature_entity: "Temperatursensor", humidity_entity: "Feuchtigkeitssensor",
    battery_entity: "Batteriesensor", show_forecast: "Vorhersage anzeigen", show_controls: "Steuerung anzeigen",
  },
  es: {
    entity: "Entidad", name: "Nombre", secondary: "Información secundaria", icon: "Icono",
    icon_color: "Color del icono", variant: "Variante", layout: "Diseño",
    show_icon: "Mostrar icono", show_state: "Mostrar estado", tap_action: "Acción al tocar",
    hold_action: "Acción al mantener", double_tap_action: "Acción de doble toque",
    temperature_entity: "Sensor de temperatura", humidity_entity: "Sensor de humedad",
    battery_entity: "Sensor de batería", show_forecast: "Mostrar pronóstico", show_controls: "Mostrar controles",
  },
  fr: {
    entity: "Entité", name: "Nom", secondary: "Information secondaire", icon: "Icône",
    icon_color: "Couleur de l’icône", variant: "Variante", layout: "Disposition",
    show_icon: "Afficher l’icône", show_state: "Afficher l’état", tap_action: "Action au toucher",
    hold_action: "Action au maintien", double_tap_action: "Action au double toucher",
    temperature_entity: "Capteur de température", humidity_entity: "Capteur d’humidité",
    battery_entity: "Capteur de batterie", show_forecast: "Afficher les prévisions", show_controls: "Afficher les commandes",
  },
  nl: {
    entity: "Entiteit", name: "Naam", secondary: "Secundaire informatie", icon: "Pictogram",
    icon_color: "Pictogramkleur", variant: "Variant", layout: "Indeling",
    show_icon: "Pictogram tonen", show_state: "Status tonen", tap_action: "Tikactie",
    hold_action: "Vasthoudactie", double_tap_action: "Dubbeltikactie",
    temperature_entity: "Temperatuursensor", humidity_entity: "Vochtigheidssensor",
    battery_entity: "Batterijsensor", show_today: "Afval van vandaag tonen",
    today_entity: "Sensor voor afval van vandaag", show_tomorrow: "Afval van morgen tonen",
    tomorrow_entity: "Sensor voor afval van morgen", show_forecast: "Voorspelling tonen", show_controls: "Bediening tonen",
  },
};

export const localize = (hass: HomeAssistant | undefined, key: string): string => {
  const language = hass?.language?.split("-")[0] ?? "en";
  return translations[language]?.[key] ?? translations.en[key] ??
    key.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
};

const helpers: Record<string, string> = {
  entity: "The Home Assistant entity shown and controlled by this card.",
  name_mode: "Choose whether the card uses the entity name, a custom name, or no name.",
  name: "Used when Name is set to Use custom name.",
  secondary: "Optional supporting text shown below the main name or state.",
  icon: "Optional icon override. Leave empty to use the card's recommended icon.",
  variant: "Choose the upstream layout or behavior represented by this unified component.",
  icon_type: "Choose an icon, the entity picture when available, or no icon.",
  layout: "Automatic uses the layout designed for this card. Horizontal and Vertical override it.",
  fill_container: "Makes the card stretch to fill the available dashboard grid cell.",
  primary_info: "Choose the main text displayed by the card.",
  secondary_info: "Choose the supporting text displayed below the primary information.",
  tap_action: "What happens when the card is tapped.",
  hold_action: "What happens when the card is pressed and held.",
  double_tap_action: "What happens when the card is tapped twice.",
  temperature_entity: "Optional sensor used when temperature comes from a separate entity.",
  humidity_entity: "Optional sensor used when humidity comes from a separate entity.",
  battery_entity: "Optional sensor used to display a separate battery level.",
  disk_entity: "Sensor containing disk or volume usage.",
  memory_entity: "Sensor containing memory usage as a percentage.",
  cpu_entity: "Sensor containing total CPU utilization as a percentage.",
  disk_name: "Friendly label shown for the disk slot.",
  disk_icon: "Icon shown in the disk tile.",
  disk_color: "Accent color used by the disk tile.",
  temperature_name: "Friendly label shown for the temperature slot.",
  temperature_icon: "Icon shown next to temperature.",
  temperature_color: "Accent and outer-ring color used for temperature.",
  temperature_max: "Maximum value represented by a complete outer ring.",
  memory_name: "Friendly label shown for the memory slot.",
  memory_icon: "Icon shown next to memory usage.",
  memory_color: "Accent and middle-ring color used for memory.",
  memory_max: "Maximum value represented by a complete middle ring.",
  cpu_name: "Friendly label shown for the CPU slot.",
  cpu_icon: "Icon shown next to CPU usage.",
  cpu_color: "Accent and inner-ring color used for CPU.",
  cpu_max: "Maximum value represented by a complete inner ring.",
  graph_span: "Source-compatible history range such as 1d; retained for YAML compatibility.",
  chart_type: "The upstream NAS design uses radial utilization rings.",
  graph_entity: "Sensor whose history is plotted in the card.",
  eta_entity: "Optional sensor containing an estimated arrival time.",
  address_entity: "Optional sensor containing a location or address.",
  min_entity: "Optional sensor used as the lower comparison value.",
  max_entity: "Optional sensor used as the upper comparison value.",
  show_today: "Shows a compact Today summary when the selected sensor contains a real collection value.",
  today_entity: "Sensor containing the waste type collected today. Empty and no-collection values are hidden.",
  show_tomorrow: "Shows a compact Tomorrow summary when the selected sensor contains a real collection value.",
  tomorrow_entity: "Sensor containing the waste type collected tomorrow. Empty and no-collection values are hidden.",
  datetime_entity: "Date and time helper controlled by this card.",
  series_2_entity: "Optional second sensor displayed in the chart legend.",
  series_3_entity: "Optional third sensor displayed in the chart legend.",
  ulm_card_alarm_time_step: "Minutes added or removed by each alarm-time button.",
  ulm_card_alarm_time_collapse: "Hides the time controls while the alarm is off.",
  ulm_card_alarm_time_horizontal: "Places the alarm details and time controls side by side.",
  ulm_card_alarm_time_icon: "Icon shown beside the alarm name and state.",
  ulm_card_alarm_time_color: "Accent color used while the alarm is active.",
  ulm_custom_card_camera_title: "Shows the camera icon, name, and label above the live image.",
  ulm_custom_card_camera_name: "Friendly camera name shown when the title is enabled.",
  ulm_custom_card_camera_label: "Supporting camera status text shown below the name.",
  ulm_custom_card_camera_aspect_ratio: "Image aspect ratio such as 16 / 9 or 4 / 3.",
  ulm_card_media_player_with_controls_name: "Friendly name shown for the Chromecast or media player.",
  ulm_card_power_details_entity: "Sensor whose current value and history are plotted.",
  ulm_card_power_details_name: "Friendly heading shown above the power history chart.",
  ulm_card_power_details_hours: "Number of hours represented by the history chart.",
  ulm_card_power_details_height: "Height of the source-compatible history chart.",
  ulm_card_power_details_24hour: "Uses 24-hour labels when chart time labels are available.",
  lock_entity: "Optional lock entity controlled alongside the door sensor.",
  navigation_path: "Dashboard path opened when the navigation card is tapped.",
  show_forecast: "Displays upcoming weather forecast information when available.",
  show_controls: "Displays controls supported by the selected entity.",
  show_graph: "Displays recent sensor history when available.",
  use_entity_picture: "Uses the entity picture instead of the selected icon.",
  console_platform: "Selects the console branding and default icon.",
  collapse_entity: "Optional input boolean that collapses or expands the scene buttons.",
  collapsed: "Starts the scene collection in its compact collapsed state.",
  ulm_card_weather_backdrop: "Adds a condition-based background to the weather card.",
  ulm_card_weather_primary_info: "Choose whether today's forecast high and low appear beside the current conditions.",
  ulm_card_weather_secondary_info: "Choose whether precipitation information appears below the current conditions.",
  ulm_card_light_enable_slider: "Lets you change brightness directly from the card.",
  ulm_card_light_enable_slider_minSet: "Lowest brightness percentage available on the slider.",
  ulm_card_light_enable_slider_maxSet: "Highest brightness percentage available on the slider.",
  ulm_card_light_enable_collapse: "Hides brightness controls while the light is off.",
  ulm_card_light_enable_horizontal: "Places the icon, details, and controls in a wider row.",
  ulm_card_light_enable_color: "Uses the light entity's RGB color for active card accents.",
  ulm_card_light_force_background_color: "Uses the active light color as the card background.",
  ulm_card_light_enable_buttons: "Adds Low, Medium, and High brightness shortcuts.",
  ulm_card_light_brightness_low: "Brightness percentage used by the Low button.",
  ulm_card_light_brightness_medium: "Brightness percentage used by the Medium button.",
  ulm_card_light_brightness_high: "Brightness percentage used by the High button.",
  ulm_card_battery_battery_level_danger: "Battery percentages at or below this value use the critical color.",
  ulm_card_battery_battery_level_warning: "Battery percentages at or below this value use the warning color.",
  ulm_card_battery_charging_animation: "Shows a visual charging animation when charging is detected.",
  ulm_card_media_player_enable_art: "Uses the current album, program, or media image when available.",
  ulm_card_media_player_enable_controls: "Adds previous, play/pause, and next buttons.",
  ulm_card_media_player_enable_volume_slider: "Lets you adjust the media player's volume from the card.",
  ulm_card_cover_enable_slider: "Lets you set the cover position directly from the card.",
  ulm_card_cover_slider_min: "Lowest position percentage available on the slider.",
  ulm_card_cover_slider_max: "Highest position percentage available on the slider.",
  ulm_card_fan_enable_slider: "Lets you set fan speed directly from the card.",
  ulm_card_fan_slider_min: "Lowest fan speed percentage available on the slider.",
  ulm_card_fan_slider_max: "Highest fan speed percentage available on the slider.",
  ulm_card_fan_enable_button: "Adds a button that toggles fan oscillation.",
  ulm_card_fan_button_icon: "Icon displayed on the oscillation button.",
  ulm_card_binary_sensor_show_last_changed: "Displays how long ago the sensor changed state.",
  ulm_card_binary_sensor_alert_show_last_changed: "Displays how long ago the alert changed state.",
  ulm_custom_card_bar_card_color: "Color used for the filled portion of the horizontal bar.",
  ulm_custom_card_bar_card_icon: "Optional icon override for the circular header icon.",
  ulm_custom_card_bar_card_icon_color: "Optional accent color for the header icon and its circle.",
  ulm_custom_card_bar_card_indicator: "Shows the current-value indicator at the leading edge of the bar.",
  ulm_custom_card_bar_card_max: "Entity value represented by a completely filled bar.",
  ulm_custom_card_bar_card_min: "Entity value represented by an empty bar.",
  ulm_custom_card_bar_card_name: "Optional name displayed below the current value.",
  ulm_custom_card_bar_card_show_icon: "Shows or hides the complete icon and text header above the bar.",
  ulm_custom_card_bar_card_value: "Displays the entity value at the right side of the bar.",
  ulm_custom_card_washer_power: "Sensor used to show the washer's current power consumption.",
  ulm_card_homeassistant_entity: "Optional overall update-status entity used by legacy configurations.",
  ulm_card_homeassistant_core: "Update, sensor, or binary sensor containing installed and latest Core versions.",
  ulm_card_homeassistant_supervisor: "Update, sensor, or binary sensor containing installed and latest Supervisor versions.",
  ulm_card_homeassistant_os: "Update, sensor, or binary sensor containing installed and latest Home Assistant OS versions.",
  tablet_button_usb_entity: "Switch or helper toggled by the green USB control.",
  tablet_button_motion_entity: "Motion or presence entity toggled by the green motion control.",
  tablet_button_display_entity: "Switch or helper toggled by the green display control.",
  tablet_restart_entity: "Button entity pressed by the blue restart control.",
  tablet_maintenance_entity: "Switch or helper toggled by the orange maintenance control.",
  tablet_reload_entity: "Button entity pressed by the blue reload control.",
  tablet_ram_entity: "Sensor shown in the centered RAM metric.",
  tablet_disk_entity: "Sensor shown in the centered Disk metric.",
  tablet_power_entity: "Entity shown in the centered Power metric.",
  ulm_card_person_entity: "Person shown by this card.",
  ulm_card_person_use_entity_picture: "Uses the person's entity picture instead of the configured face icon.",
  ulm_card_person_zone1: "Zone entity used for the first custom location badge.",
  ulm_card_person_zone2: "Zone entity used for the second custom location badge.",
  ulm_address: "Sensor whose state is shown as the current address.",
  ulm_address_locality: "Sensor whose Locality attribute is shown as the current location.",
  ulm_card_person_driving_entity: "Binary sensor that changes the badge and label while driving.",
  ulm_card_person_battery_entity: "Sensor containing the person's device battery percentage.",
  ulm_card_person_battery_state_entity: "Sensor whose state indicates whether the battery is charging.",
  ulm_card_person_commute_entity: "Sensor containing commute time in minutes.",
  ulm_card_person_cummute_icon: "Icon shown beside the commute time.",
  ulm_multiline: "Places battery and commute details on a separate row.",
};

export const editorHelper = (key: string): string | undefined => helpers[key];
