import type { HomeAssistant } from "./types";

const translations: Record<string, Record<string, string>> = {
  en: {
    entity: "Entity", name: "Custom name", name_mode: "Name", secondary: "Custom secondary information", icon: "Icon",
    icon_color: "Icon color", variant: "Card style", layout: "Layout",
    icon_type: "Icon type", fill_container: "Fill container",
    primary_info: "Primary information", secondary_info: "Secondary information",
    show_icon: "Show icon", show_state: "Show state", tap_action: "Tap action",
    hold_action: "Hold action", double_tap_action: "Double-tap action",
    collapse_entity: "Collapse helper", collapsed: "Show collapsed",
    weather_entity: "Weather entity", settings_path: "Settings navigation path",
    temperature_entity: "Temperature sensor", humidity_entity: "Humidity sensor",
    battery_entity: "Battery sensor", graph_entity: "Graph sensor", eta_entity: "ETA sensor",
    consumption_entity: "Power consumption sensor", fan_entity: "External fan entity",
    label_use_temperature: "Show temperature label", label_use_brightness: "Show brightness label",
    input_select_entity: "Room selection helper", input_select_option: "Room selection option",
    thermostat_minimum_temp_spread: "Minimum setpoint spread", thermostat_temp_step: "Temperature step",
    date_entity: "Date sensor", download_entity: "Download speed sensor",
    upload_entity: "Upload speed sensor", ping_entity: "Ping sensor",
    wifi_tracker_entity: "Wi-Fi tracker", gps_tracker_entity: "GPS tracker",
    findmy_script_entity: "Find-my-phone script",
    disk_entity: "Disk usage sensor", memory_entity: "Memory usage sensor", cpu_entity: "CPU usage sensor",
    power_entity: "Power sensor", energy_entity: "Energy sensor", time_entity: "Runtime sensor",
    black_entity: "Black toner sensor", yellow_entity: "Yellow toner sensor",
    magenta_entity: "Magenta toner sensor", cyan_entity: "Cyan toner sensor",
    minimum: "Minimum value", maximum: "Maximum value",
    disk_name: "Disk label", disk_icon: "Disk icon", disk_color: "Disk color",
    temperature_name: "Temperature label", temperature_icon: "Temperature icon", temperature_color: "Temperature color",
    temperature_max: "Temperature chart maximum",
    memory_name: "Memory label", memory_icon: "Memory icon", memory_color: "Memory color",
    memory_max: "Memory chart maximum",
    cpu_name: "CPU label", cpu_icon: "CPU icon", cpu_color: "CPU color", cpu_max: "CPU chart maximum",
    graph_span: "History range", chart_type: "Chart style",
    address_entity: "Address sensor", min_entity: "Minimum sensor", max_entity: "Maximum sensor",
    show_today: "Show today's collection summary", today_entity: "Today's collection summary sensor",
    show_tomorrow: "Show tomorrow's collection summary", tomorrow_entity: "Tomorrow's collection summary sensor",
    show_forecast: "Show forecast", show_controls: "Show controls", show_graph: "Show graph",
    use_entity_picture: "Use entity picture", graph_hours: "Graph hours", console_platform: "Console platform",
    ulm_card_weather_backdrop: "Show weather background",
    ulm_card_weather_primary_info: "Main weather information",
    ulm_card_weather_secondary_info: "Additional weather information",
    ulm_card_vacuum_camera: "Vacuum map camera",
    ulm_card_vacuum_camera_toggle: "Show map only while cleaning",
    ulm_card_vacuum_room: "Room-cleaning script",
    ulm_card_vacuum_room_icon: "Room-cleaning icon",
    ulm_card_vacuum_force_background_color: "Color the card while active",
    ulm_card_vertical_button_color: "Active color",
    ulm_card_vertical_button_state: "Active state or input-select option",
    ulm_card_light_enable_slider: "Show brightness slider",
    ulm_card_light_enable_slider_minSet: "Minimum slider brightness",
    ulm_card_light_enable_slider_maxSet: "Maximum slider brightness",
    ulm_card_light_enable_collapse: "Collapse controls when light is off",
    ulm_card_light_enable_horizontal: "Use horizontal layout",
    ulm_card_light_enable_horizontal_wide: "Use a wide horizontal control",
    ulm_card_light_color: "Light accent color",
    ulm_card_light_enable_color: "Use the light's current color",
    ulm_card_light_force_background_color: "Color the card when light is on",
    ulm_card_light_enable_buttons: "Show brightness preset buttons",
    ulm_card_light_brightness_low: "Low brightness preset",
    ulm_card_light_brightness_medium: "Medium brightness preset",
    ulm_card_light_brightness_high: "High brightness preset",
    ulm_card_battery_battery_level_danger: "Low battery threshold",
    ulm_card_battery_battery_level_warning: "Battery warning threshold",
    ulm_card_battery_attribute: "Battery level attribute",
    ulm_card_battery_battery_state_entity_id: "Charging state entity",
    ulm_card_battery_charger_type_entity_id: "Charger type entity",
    ulm_card_battery_charging_animation: "Animate while charging",
    ulm_card_battery_color_battery_level_danger: "Low battery color",
    ulm_card_battery_color_battery_level_warning: "Battery warning color",
    ulm_card_battery_color_battery_level_ok: "Healthy battery color",
    ulm_card_battery_name: "Battery name",
    ulm_card_media_player_enable_art: "Show media artwork",
    ulm_card_media_player_enable_controls: "Show playback controls",
    ulm_card_media_player_enable_volume_slider: "Show volume slider",
    ulm_card_media_player_enable_volume_buttons: "Show volume buttons",
    ulm_card_media_player_enable_volume_adjust: "Volume button step",
    ulm_card_media_player_collapsible: "Collapse controls while inactive",
    ulm_card_media_player_idle_off: "Treat idle as inactive",
    ulm_card_media_player_player_controls_entity: "Playback control entity",
    ulm_card_media_player_more_info: "Show artist and album details",
    ulm_card_media_player_power_button: "Show power button",
    ulm_card_media_player_force_background_color: "Color the card while active",
    ulm_card_media_player_color: "Media accent color",
    ulm_card_generic_color: "Generic card accent color",
    ulm_card_generic_force_background_color: "Color the generic card while active",
    ulm_card_generic_swap_color: "Swapped card accent color",
    ulm_card_generic_swap_force_background_color: "Color the swapped card while active",
    ulm_card_graph_color: "Primary graph color",
    ulm_card_graph_color2: "Secondary graph color",
    ulm_card_graph_entity2: "Secondary graph entity",
    ulm_card_graph_group_by: "Graph grouping",
    ulm_card_graph_hours: "Graph history hours",
    ulm_card_graph_icon_color: "Graph icon color",
    ulm_card_graph_line_width: "Graph line width",
    ulm_card_graph_points: "Graph points per hour",
    ulm_card_graph_type: "Graph style",
    ulm_card_navigate_color: "Navigation accent color",
    ulm_card_thermostat_enable_collapse: "Collapse thermostat controls",
    ulm_card_thermostat_enable_controls: "Show temperature controls",
    ulm_card_thermostat_enable_hvac_modes: "Show HVAC modes",
    ulm_card_thermostat_enable_background_color: "Color active thermostat",
    ulm_card_thermostat_enable_display_temperature: "Show current temperature",
    ulm_card_thermostat_enable_horizontal: "Use horizontal thermostat layout",
    ulm_card_cover_enable_slider: "Show position slider",
    ulm_card_cover_color: "Cover accent color",
    ulm_card_cover_display_left_right: "Use left and right controls",
    ulm_card_cover_enable_controls: "Show open, stop, and close controls",
    ulm_card_cover_enable_horizontal: "Use horizontal cover layout",
    ulm_card_cover_enable_tilt: "Show tilt controls",
    ulm_card_cover_favorite_percentage: "Favorite cover position",
    ulm_card_cover_force_background_color: "Color the card while open",
    ulm_card_cover_garage_large: "Use large garage icons",
    ulm_card_cover_icon: "Cover icon",
    ulm_card_cover_invert_percent: "Invert cover percentage",
    ulm_card_cover_name: "Cover name",
    ulm_card_cover_show_last_changed: "Show when the cover last changed",
    ulm_card_invert_percent: "Invert cover percentage (legacy)",
    ulm_card_cover_slider_min: "Minimum cover position",
    ulm_card_cover_slider_max: "Maximum cover position",
    ulm_card_fan_enable_slider: "Show speed slider",
    ulm_card_fan_slider_min: "Minimum fan speed",
    ulm_card_fan_slider_max: "Maximum fan speed",
    ulm_card_fan_enable_button: "Show oscillation button",
    ulm_card_fan_button_icon: "Oscillation button icon",
    ulm_card_fan_button_service: "Oscillation service",
    ulm_card_fan_color: "Fan accent color",
    ulm_card_fan_enable_collapse: "Collapse controls while off",
    ulm_card_fan_enable_horizontal: "Use horizontal fan layout",
    ulm_card_fan_force_background_color: "Color the card while on",
    ulm_card_fan_hum_attribute: "Humidity attribute",
    ulm_card_fan_icon: "Fan icon",
    ulm_card_fan_name: "Fan name",
    ulm_card_fan_oscillate_attribute: "Oscillation attribute",
    ulm_card_fan_temp_attribute: "Temperature attribute",
    ulm_card_binary_sensor_color: "Binary sensor accent color",
    ulm_card_binary_sensor_force_background_color: "Color the card while active",
    ulm_card_binary_sensor_icon: "Binary sensor icon",
    ulm_card_binary_sensor_name: "Binary sensor name",
    ulm_card_binary_sensor_show_last_changed: "Show when the state last changed",
    ulm_card_binary_sensor_alert_color: "Alert accent color",
    ulm_card_binary_sensor_alert_force_background_color: "Color the alert card while active",
    ulm_card_binary_sensor_alert_icon: "Alert icon",
    ulm_card_binary_sensor_alert_name: "Alert name",
    ulm_card_binary_sensor_alert_show_last_changed: "Show when the alert last changed",
    ulm_card_input_boolean_color: "Input boolean accent color",
    ulm_card_input_boolean_force_background_color: "Color the card while on",
    ulm_card_input_boolean_icon: "Input boolean icon",
    ulm_card_input_boolean_name: "Input boolean name",
    ulm_custom_card_bar_card_color: "Bar color",
    ulm_custom_card_bar_card_icon: "Header icon",
    ulm_custom_card_bar_card_icon_color: "Icon color",
    ulm_custom_card_bar_card_indicator: "Show bar indicator",
    ulm_custom_card_bar_card_max: "Maximum value",
    ulm_custom_card_bar_card_min: "Minimum value",
    ulm_custom_card_bar_card_name: "Header name",
    ulm_custom_card_bar_card_show_icon: "Show icon and header",
    ulm_custom_card_bar_card_value: "Show value inside bar",
    ulm_custom_card_washer_power: "Power sensor",
    ulm_custom_card_washer_remote_control: "Remote control status",
    ulm_custom_card_washer_machine_state: "Machine state",
    ulm_custom_card_washer_machine_stop_state: "Stopped state value",
    ulm_custom_card_washer_job_state: "Current program stage",
    ulm_custom_card_washer_job_progress: "Program progress",
    ulm_custom_card_washer_job_states: "Program stages",
    ulm_custom_card_washer_delayed_start: "Delayed start toggle",
    ulm_custom_card_washer_delayed_starttime: "Delayed start time",
    ulm_custom_card_washer_label_idle: "Idle label",
    ulm_custom_card_washer_label_configuring: "Configuring label",
    ulm_custom_card_washer_label_running: "Running label",
    ulm_custom_card_washer_start_action: "Start action",
    ulm_custom_card_washer_pause_action: "Pause action",
    ulm_custom_card_washer_stop_action: "Stop action",
    door_entity: "Door entity",
    finished_entity: "Finished entity",
    battery_state_entity: "Battery state entity",
    charger_type_entity: "Charger type entity",
    secondary_entity: "Secondary entity",
    darkMode: "Dark mode",
    language: "Language",
    showAzimuth: "Show azimuth",
    showElevation: "Show elevation",
    timeFormat: "Time format",
    title: "Title",
    ulm_custom_card_iAbadia_battery_chip_entity: "Battery entity",
    ulm_custom_card_iAbadia_battery_chip_icon: "Battery chip icon",
    ulm_custom_card_iAbadia_battery_chip_warning: "Warning threshold",
    ulm_custom_card_iAbadia_battery_chip_danger: "Danger threshold",
    ulm_custom_card_imswel_medias_index: "Media item index",
    ulm_custom_card_imswel_medias_platform: "Media platform",
    ulm_card_homeassistant_entity: "Overall updates entity",
    ulm_card_homeassistant_core: "Home Assistant Core update entity",
    ulm_card_homeassistant_supervisor: "Supervisor update entity",
    ulm_card_homeassistant_os: "Home Assistant OS update entity",
    tablet_button_usb_entity: "USB control",
    tablet_button_motion_entity: "Motion control",
    tablet_button_display_entity: "Display control",
    tablet_restart_entity: "Restart button",
    tablet_maintenance_entity: "Maintenance mode control",
    tablet_reload_entity: "Reload button",
    tablet_ram_entity: "RAM usage sensor",
    tablet_disk_entity: "Disk usage sensor",
    tablet_power_entity: "Power state entity",
    ulm_card_person_entity: "Person",
    ulm_card_person_use_entity_picture: "Use person picture",
    ulm_card_person_zone1: "First known zone",
    ulm_card_person_zone2: "Second known zone",
    ulm_address: "Address sensor",
    ulm_address_locality: "Address locality sensor",
    ulm_card_person_driving_entity: "Driving status sensor",
    ulm_card_person_battery_entity: "Battery level sensor",
    ulm_card_person_battery_state_entity: "Battery charging-state sensor",
    ulm_card_person_commute_entity: "Commute time sensor",
    ulm_card_person_cummute_icon: "Commute icon",
    ulm_multiline: "Use multiline layout",
    ulm_custom_card_device_tracker_icon: "Device icon",
    ulm_custom_card_device_tracker_tracker_1_entity: "First tracker",
    ulm_custom_card_device_tracker_tracker_1_type: "First tracker type",
    ulm_custom_card_device_tracker_tracker_2_entity: "Second tracker",
    ulm_custom_card_device_tracker_tracker_2_type: "Second tracker type",
    group_lights: "Lights group", group_motions: "Motion group", group_doors: "Doors group",
    group_windows: "Windows group", group_outlets: "Outlets group", group_tv: "Televisions group",
    group_water: "Water sensors group", group_windows_shutters: "Shutters group",
    temperature: "Temperature sensor", humidity: "Humidity sensor",
    ulm_custom_card_eraycetinay_lock_tap_control: "Control lock on tap",
    ulm_custom_card_eraycetinay_lock_only_open: "Always open on tap",
    ulm_custom_card_eraycetinay_lock_battery_level: "Lock battery sensor",
    ulm_custom_card_eraycetinay_lock_battery_warning: "Battery warning threshold",
    ulm_custom_card_eraycetinay_lock_battery_warning_low: "Critical battery threshold",
    ulm_custom_card_eraycetinay_lock_door_open: "Door open sensor",
    ulm_custom_card_eraycetinay_lock_battery_sensor_binary: "Battery sensor is binary",
    ulm_custom_card_eraycetinay_lock_battery_sensor_binary_low_state: "Binary low-battery state",
    ulm_custom_card_esh_room_light_entity: "Room light",
    ulm_custom_card_esh_room_climate_entity: "Room climate",
    ulm_custom_card_esh_room_cover_entity: "Room cover",
    ulm_card_esh_room_light_icon_on: "Light-on icon",
    ulm_card_esh_room_light_icon_off: "Light-off icon",
    ulm_card_esh_room_cover_icon_open: "Open-cover icon",
    ulm_card_esh_room_cover_icon_closed: "Closed-cover icon",
    ulm_card_dynamic_color: "Use the light color as the room accent",
    ulm_card_esh_welcome_collapse: "Welcome collapse helper",
    ulm_weather: "Weather provider",
    nav_1: "First navigation path", icon_1: "First navigation icon", name_1: "First navigation name", color_1: "First navigation color",
    nav_2: "Second navigation path", icon_2: "Second navigation icon", name_2: "Second navigation name", color_2: "Second navigation color",
    nav_3: "Third navigation path", icon_3: "Third navigation icon", name_3: "Third navigation name", color_3: "Third navigation color",
    nav_4: "Fourth navigation path", icon_4: "Fourth navigation icon", name_4: "Fourth navigation name", color_4: "Fourth navigation color",
    nav_5: "Fifth navigation path", icon_5: "Fifth navigation icon", name_5: "Fifth navigation name", color_5: "Fifth navigation color",
  },
  de: {
    entity: "Entität", name: "Name", secondary: "Sekundärinformation", icon: "Symbol",
    icon_color: "Symbolfarbe", variant: "Variante", layout: "Layout",
    show_icon: "Symbol anzeigen", show_state: "Status anzeigen", tap_action: "Tippaktion",
    hold_action: "Halteaktion", double_tap_action: "Doppeltippaktion",
    temperature_entity: "Temperatursensor", humidity_entity: "Feuchtigkeitssensor",
    battery_entity: "Batteriesensor", show_forecast: "Vorhersage anzeigen", show_controls: "Steuerung anzeigen",
  },
  es: {
    entity: "Entidad", name: "Nombre", secondary: "Información secundaria", icon: "Icono",
    icon_color: "Color del icono", variant: "Variante", layout: "Diseño",
    show_icon: "Mostrar icono", show_state: "Mostrar estado", tap_action: "Acción al tocar",
    hold_action: "Acción al mantener", double_tap_action: "Acción de doble toque",
    temperature_entity: "Sensor de temperatura", humidity_entity: "Sensor de humedad",
    battery_entity: "Sensor de batería", show_forecast: "Mostrar pronóstico", show_controls: "Mostrar controles",
  },
  fr: {
    entity: "Entité", name: "Nom", secondary: "Information secondaire", icon: "Icône",
    icon_color: "Couleur de l’icône", variant: "Variante", layout: "Disposition",
    show_icon: "Afficher l’icône", show_state: "Afficher l’état", tap_action: "Action au toucher",
    hold_action: "Action au maintien", double_tap_action: "Action au double toucher",
    temperature_entity: "Capteur de température", humidity_entity: "Capteur d’humidité",
    battery_entity: "Capteur de batterie", show_forecast: "Afficher les prévisions", show_controls: "Afficher les commandes",
  },
  nl: {
    entity: "Entiteit", name: "Naam", secondary: "Secundaire informatie", icon: "Pictogram",
    icon_color: "Pictogramkleur", variant: "Variant", layout: "Indeling",
    show_icon: "Pictogram tonen", show_state: "Status tonen", tap_action: "Tikactie",
    hold_action: "Vasthoudactie", double_tap_action: "Dubbeltikactie",
    temperature_entity: "Temperatuursensor", humidity_entity: "Vochtigheidssensor",
    battery_entity: "Batterijsensor", show_today: "Afval van vandaag tonen",
    today_entity: "Sensor voor afval van vandaag", show_tomorrow: "Afval van morgen tonen",
    tomorrow_entity: "Sensor voor afval van morgen", show_forecast: "Voorspelling tonen", show_controls: "Bediening tonen",
  },
};

export const localize = (hass: HomeAssistant | undefined, key: string): string => {
  const language = hass?.language?.split("-")[0] ?? "en";
  return translations[language]?.[key] ?? translations.en[key] ??
    key.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
};

const helpers: Record<string, string> = {
  entity: "The Home Assistant entity shown and controlled by this card.",
  name_mode: "Choose whether the card uses the entity name, a custom name, or no name.",
  name: "Used when Name is set to Use custom name.",
  secondary: "Optional supporting text shown below the main name or state.",
  icon: "Optional icon override. Leave empty to use the card's recommended icon.",
  variant: "Choose the upstream layout or behavior represented by this unified component.",
  icon_type: "Choose an icon, the entity picture when available, or no icon.",
  layout: "Automatic uses the layout designed for this card. Horizontal and Vertical override it.",
  fill_container: "Makes the card stretch to fill the available dashboard grid cell.",
  primary_info: "Choose the main text displayed by the card.",
  secondary_info: "Choose the supporting text displayed below the primary information.",
  tap_action: "What happens when the card is tapped.",
  hold_action: "What happens when the card is pressed and held.",
  double_tap_action: "What happens when the card is tapped twice.",
  weather_entity: "Weather entity used by the source-specific welcome or date presentation.",
  settings_path: "Dashboard path opened by the welcome settings button.",
  collapse_entity: "Input boolean that hides or shows the welcome scene pills.",
  collapsed: "Forces the welcome scene pills to stay hidden.",
  show_controls: "Shows the controls defined by the pinned source design.",
  show_forecast: "Loads the daily weather forecast used by the detailed source design.",
  ulm_card_vacuum_camera: "Optional camera entity whose entity picture is shown as the vacuum map.",
  ulm_card_vacuum_camera_toggle: "Shows the map only while the vacuum is cleaning, mowing, or mopping.",
  ulm_card_vacuum_room: "Optional script called by the fourth room-cleaning control.",
  ulm_card_vacuum_room_icon: "Icon shown for the optional room-cleaning control.",
  ulm_card_vacuum_force_background_color: "Uses the state color as the card background while the vacuum is active.",
  ulm_card_vertical_button_color: "Accent color used when the entity matches the configured active state.",
  ulm_card_vertical_button_state: "State that activates the button, and the option selected for input_select entities.",
  temperature_entity: "Optional sensor used when temperature comes from a separate entity.",
  humidity_entity: "Optional sensor used when humidity comes from a separate entity.",
  battery_entity: "Optional sensor used to display a separate battery level.",
  consumption_entity: "Optional power sensor appended to the outlet state while it is on.",
  fan_entity: "Optional fan toggled when the climate entity does not expose fan-only mode.",
  label_use_temperature: "Uses the room entity temperature, device temperature, or state as the card label.",
  label_use_brightness: "Uses the light brightness percentage as the label while the room entity is on.",
  input_select_entity: "Optional input select changed by the room card double-tap action.",
  input_select_option: "Option selected on the configured room helper.",
  thermostat_minimum_temp_spread: "Smallest allowed difference between low and high dual setpoints.",
  thermostat_temp_step: "Temperature increment used by the thermostat controls.",
  date_entity: "Sensor containing the source card's preformatted date text.",
  download_entity: "Speedtest download sensor shown by the card and refreshed by the test action.",
  upload_entity: "Speedtest upload sensor shown by the card and refreshed by the test action.",
  ping_entity: "Speedtest ping sensor refreshed together with download and upload.",
  wifi_tracker_entity: "Device tracker used by the source popup's Wi-Fi glance.",
  gps_tracker_entity: "Device tracker used by the source popup's GPS glance and map.",
  findmy_script_entity: "Script invoked by the source popup's phone finder control.",
  ulm_card_input_datetime_name: "Optional source-compatible name shown in the datetime header.",
  ulm_card_input_number_name: "Optional source-compatible name shown in the input-number header.",
  ulm_custom_card_irmajavi_entities_icon: "Icon shown before the main Entities heading.",
  ulm_custom_card_irmajavi_entities_name: "Heading shown above the four entity values.",
  ulm_custom_card_irmajavi_entities_entity_1: "Entity shown in the first metric slot.",
  ulm_custom_card_irmajavi_entities_entity_2: "Entity shown in the second metric slot.",
  ulm_custom_card_irmajavi_entities_entity_3: "Entity shown in the third metric slot.",
  ulm_custom_card_irmajavi_entities_entity_4: "Entity shown in the fourth metric slot.",
  ulm_custom_card_irmajavi_entities_name_1: "Label shown below the first metric value.",
  ulm_custom_card_irmajavi_entities_name_2: "Label shown below the second metric value.",
  ulm_custom_card_irmajavi_entities_name_3: "Label shown below the third metric value.",
  ulm_custom_card_irmajavi_entities_name_4: "Label shown below the fourth metric value.",
  ulm_custom_card_irmajavi_speedtest_router_name: "Router name shown below the Wi-Fi icon.",
  ulm_custom_card_irmajavi_speedtest_router_model: "Router model shown below the router name.",
  ulm_custom_card_irmajavi_speedtest_color: "Accent color used by the Wi-Fi icon.",
  ulm_custom_card_irmajavi_weather_entity_1: "Entity shown in the first weather metric slot.",
  ulm_custom_card_irmajavi_weather_entity_2: "Entity shown in the second weather metric slot.",
  ulm_custom_card_irmajavi_weather_entity_3: "Entity shown in the third weather metric slot.",
  ulm_custom_card_irmajavi_weather_entity_4: "Entity shown in the fourth weather metric slot.",
  ulm_custom_card_irmajavi_weather_name_1: "Label shown below the first weather metric.",
  ulm_custom_card_irmajavi_weather_name_2: "Label shown below the second weather metric.",
  ulm_custom_card_irmajavi_weather_name_3: "Label shown below the third weather metric.",
  ulm_custom_card_irmajavi_weather_name_4: "Label shown below the fourth weather metric.",
  disk_entity: "Sensor containing disk or volume usage.",
  memory_entity: "Sensor containing memory usage as a percentage.",
  cpu_entity: "Sensor containing total CPU utilization as a percentage.",
  disk_name: "Friendly label shown for the disk slot.",
  disk_icon: "Icon shown in the disk tile.",
  disk_color: "Accent color used by the disk tile.",
  temperature_name: "Friendly label shown for the temperature slot.",
  temperature_icon: "Icon shown next to temperature.",
  temperature_color: "Accent and outer-ring color used for temperature.",
  temperature_max: "Maximum value represented by a complete outer ring.",
  memory_name: "Friendly label shown for the memory slot.",
  memory_icon: "Icon shown next to memory usage.",
  memory_color: "Accent and middle-ring color used for memory.",
  memory_max: "Maximum value represented by a complete middle ring.",
  cpu_name: "Friendly label shown for the CPU slot.",
  cpu_icon: "Icon shown next to CPU usage.",
  cpu_color: "Accent and inner-ring color used for CPU.",
  cpu_max: "Maximum value represented by a complete inner ring.",
  graph_span: "Source-compatible history range such as 1d; retained for YAML compatibility.",
  chart_type: "The upstream NAS design uses radial utilization rings.",
  graph_entity: "Sensor whose history is plotted in the card.",
  eta_entity: "Optional sensor containing an estimated arrival time.",
  address_entity: "Optional sensor containing a location or address.",
  min_entity: "Optional sensor used as the lower comparison value.",
  max_entity: "Optional sensor used as the upper comparison value.",
  show_today: "Shows a compact Today summary when the selected sensor contains a real collection value.",
  today_entity: "Sensor containing the waste type collected today. Empty and no-collection values are hidden.",
  show_tomorrow: "Shows a compact Tomorrow summary when the selected sensor contains a real collection value.",
  tomorrow_entity: "Sensor containing the waste type collected tomorrow. Empty and no-collection values are hidden.",
  datetime_entity: "Date and time helper controlled by this card.",
  time_entity: "Time or runtime sensor used by the source-specific presentation.",
  news_entities: "Up to three entities shown in the compact source-compatible news feed.",
  qubino_more_info_entity: "Entity opened by the Qubino card surface, matching the source pilot-wire input select.",
  ulm_custom_card_ristou_use_entity_picture: "Uses the person's entity picture instead of the fallback face icon.",
  ulm_custom_card_ristou_use_badge: "Shows the source location or driving badge over the person icon.",
  ulm_custom_card_ristou_person_driving_entity: "Binary sensor whose active state replaces the location label with Driving.",
  ulm_custom_card_ristou_zones: "Zone entities used to resolve custom location icons and colors.",
  ulm_custom_card_ristou_find_device_script: "Optional script or button shown as the source find-device control.",
  ulm_custom_card_ristou_map_enable: "Shows the source built-in map row equivalent.",
  ulm_custom_card_ristou_map_aspect_ratio: "Aspect ratio used by the built-in map row, such as 466:200.",
  ulm_custom_card_ristou_map_hours_to_show: "Number of location-history hours requested by the source map.",
  ulm_custom_card_ristou_map_default_zoom: "Default zoom requested by the source map.",
  ulm_custom_card_ristou_camera_entity_light: "Light-theme static-map camera entity.",
  ulm_custom_card_ristou_camera_entity_dark: "Dark-theme static-map camera entity; both camera fields are required for static-map mode.",
  series_2_entity: "Optional second sensor displayed in the chart legend.",
  series_3_entity: "Optional third sensor displayed in the chart legend.",
  ulm_card_alarm_time_step: "Minutes added or removed by each alarm-time button.",
  ulm_card_alarm_time_collapse: "Hides the time controls while the alarm is off.",
  ulm_card_alarm_time_horizontal: "Places the alarm details and time controls side by side.",
  ulm_card_alarm_time_icon: "Icon shown beside the alarm name and state.",
  ulm_card_alarm_time_color: "Accent color used while the alarm is active.",
  ulm_custom_card_camera_title: "Shows the camera icon, name, and label above the live image.",
  ulm_custom_card_camera_name: "Friendly camera name shown when the title is enabled.",
  ulm_custom_card_camera_label: "Supporting camera status text shown below the name.",
  ulm_custom_card_camera_aspect_ratio: "Image aspect ratio such as 16 / 9 or 4 / 3.",
  ulm_card_media_player_with_controls_name: "Friendly name shown for the Chromecast or media player.",
  ulm_card_power_details_entity: "Sensor whose current value and history are plotted.",
  ulm_card_power_details_name: "Friendly heading shown above the power history chart.",
  ulm_card_power_details_hours: "Number of hours represented by the history chart.",
  ulm_card_power_details_height: "Height of the source-compatible history chart.",
  ulm_card_power_details_24hour: "Uses 24-hour labels when chart time labels are available.",
  ulm_custom_card_device_tracker_tracker_1_entity: "Independent device_tracker entity represented by the upper status badge.",
  ulm_custom_card_device_tracker_tracker_2_entity: "Independent device_tracker entity represented by the lower status badge.",
  ulm_custom_card_device_tracker_icon: "Main device icon shown behind the two independent tracker badges.",
  ulm_custom_card_device_tracker_tracker_1_type: "Connection type used to choose the upper badge's truthful home and away icons.",
  ulm_custom_card_device_tracker_tracker_2_type: "Connection type used to choose the lower badge's truthful home and away icons.",
  temperature: "Temperature sensor shown in the RoomView header.",
  humidity: "Humidity sensor shown in the RoomView header.",
  group_lights: "Named Home Assistant group containing the room lights.",
  group_motions: "Named Home Assistant group containing motion sensors.",
  group_doors: "Named Home Assistant group containing door sensors.",
  group_windows: "Named Home Assistant group containing window sensors.",
  group_outlets: "Named Home Assistant group containing outlets.",
  group_tv: "Named Home Assistant group containing televisions.",
  group_water: "Named Home Assistant group containing water sensors.",
  group_windows_shutters: "Named Home Assistant group containing window shutters.",
  ulm_custom_card_eraycetinay_lock_tap_control: "When enabled, tapping sends lock, unlock, or open; otherwise it opens more-info.",
  ulm_custom_card_eraycetinay_lock_only_open: "Always sends lock.open instead of switching locked and unlocked states.",
  ulm_custom_card_eraycetinay_lock_battery_level: "Percentage or binary battery sensor used for the lock warning badge.",
  ulm_custom_card_eraycetinay_lock_battery_warning: "Percentage at or below which the battery warning badge appears.",
  ulm_custom_card_eraycetinay_lock_battery_warning_low: "Percentage at or below which the battery warning becomes critical.",
  ulm_custom_card_eraycetinay_lock_door_open: "Binary sensor used to warn when the lock is locked while the door remains open.",
  ulm_custom_card_eraycetinay_lock_battery_sensor_binary: "Treats the configured battery sensor as a binary low-battery sensor.",
  ulm_custom_card_eraycetinay_lock_battery_sensor_binary_low_state: "State that means low battery when a binary sensor is configured.",
  ulm_custom_card_esh_room_light_entity: "Light shown in the first semantic room control slot.",
  ulm_custom_card_esh_room_climate_entity: "Climate entity shown in the second semantic room control slot.",
  ulm_custom_card_esh_room_cover_entity: "Cover entity shown in the second semantic room control slot when configured.",
  ulm_card_esh_room_light_icon_on: "Icon shown by the semantic light control while the light is on.",
  ulm_card_esh_room_light_icon_off: "Icon shown by the semantic light control while the light is off.",
  ulm_card_esh_room_cover_icon_open: "Icon shown by the semantic cover control while open.",
  ulm_card_esh_room_cover_icon_closed: "Icon shown by the semantic cover control while closed.",
  ulm_card_dynamic_color: "Uses the configured light's RGB color for the active room card.",
  ulm_card_esh_welcome_collapse: "Optional input_boolean toggled by the top-left collapse control.",
  ulm_weather: "Weather entity opened by the center topbar control.",
  nav_1: "Dashboard path opened by the first navigation pill.", icon_1: "Icon for the first navigation pill.", name_1: "Label for the first navigation pill.", color_1: "Source color for the first navigation pill.",
  nav_2: "Dashboard path opened by the second navigation pill.", icon_2: "Icon for the second navigation pill.", name_2: "Label for the second navigation pill.", color_2: "Source color for the second navigation pill.",
  nav_3: "Dashboard path opened by the third navigation pill.", icon_3: "Icon for the third navigation pill.", name_3: "Label for the third navigation pill.", color_3: "Source color for the third navigation pill.",
  nav_4: "Dashboard path opened by the fourth navigation pill.", icon_4: "Icon for the fourth navigation pill.", name_4: "Label for the fourth navigation pill.", color_4: "Source color for the fourth navigation pill.",
  nav_5: "Dashboard path opened by the fifth navigation pill.", icon_5: "Icon for the fifth navigation pill.", name_5: "Label for the fifth navigation pill.", color_5: "Source color for the fifth navigation pill.",
  lock_entity: "Optional lock entity controlled alongside the door sensor.",
  navigation_path: "Dashboard path opened when the navigation card is tapped.",
  show_graph: "Displays recent sensor history when available.",
  use_entity_picture: "Uses the entity picture instead of the selected icon.",
  console_platform: "Selects the console branding and default icon.",
  ulm_card_weather_backdrop: "Adds a condition-based background to the weather card.",
  ulm_card_weather_primary_info: "Choose whether today's forecast high and low appear beside the current conditions.",
  ulm_card_weather_secondary_info: "Choose whether precipitation information appears below the current conditions.",
  ulm_card_light_enable_slider: "Lets you change brightness directly from the card.",
  ulm_card_light_enable_slider_minSet: "Lowest brightness percentage available on the slider.",
  ulm_card_light_enable_slider_maxSet: "Highest brightness percentage available on the slider.",
  ulm_card_light_enable_collapse: "Hides brightness controls while the light is off.",
  ulm_card_light_enable_horizontal: "Places the icon, details, and controls in a wider row.",
  ulm_card_light_enable_horizontal_wide: "Gives the slider twice as much width as the light summary.",
  ulm_card_light_color: "Accent color used when the light is on and entity color is disabled.",
  ulm_card_light_enable_color: "Uses the light entity's RGB color for active card accents.",
  ulm_card_light_force_background_color: "Uses the active light color as the card background.",
  ulm_card_light_enable_buttons: "Adds Low, Medium, and High brightness shortcuts.",
  ulm_card_light_brightness_low: "Brightness percentage used by the Low button.",
  ulm_card_light_brightness_medium: "Brightness percentage used by the Medium button.",
  ulm_card_light_brightness_high: "Brightness percentage used by the High button.",
  ulm_card_battery_battery_level_danger: "Battery percentages at or below this value use the critical color.",
  ulm_card_battery_battery_level_warning: "Battery percentages at or below this value use the warning color.",
  ulm_card_battery_attribute: "Optional entity attribute containing the battery percentage instead of the state.",
  ulm_card_battery_battery_state_entity_id: "Entity whose charging state drives the charging icon and optional animation.",
  ulm_card_battery_charger_type_entity_id: "Entity whose wireless, AC, USB, or charging state selects the charging icon.",
  ulm_card_battery_charging_animation: "Shows a visual charging animation when charging is detected.",
  ulm_card_battery_color_battery_level_danger: "Accent used at or below the low battery threshold.",
  ulm_card_battery_color_battery_level_warning: "Accent used at or below the warning threshold.",
  ulm_card_battery_color_battery_level_ok: "Accent used above the configured warning thresholds.",
  ulm_card_battery_name: "Optional source-compatible name override.",
  ulm_card_media_player_enable_art: "Uses the current album, program, or media image when available.",
  ulm_card_media_player_enable_controls: "Adds previous, play/pause, and next buttons.",
  ulm_card_media_player_enable_volume_slider: "Lets you adjust the media player's volume from the card.",
  ulm_card_media_player_enable_volume_buttons: "Adds mute, volume-down, and volume-up controls.",
  ulm_card_media_player_enable_volume_adjust: "Exact volume-level increment used by the volume buttons.",
  ulm_card_media_player_collapsible: "Hides playback and volume controls while the player is inactive.",
  ulm_card_media_player_idle_off: "Treats the idle state like off when collapsible controls are enabled.",
  ulm_card_media_player_player_controls_entity: "Media player that receives playback and volume service calls.",
  ulm_card_media_player_more_info: "Shows artist and album metadata below the current title.",
  ulm_card_media_player_power_button: "Adds a power toggle in the top-right corner.",
  ulm_card_media_player_force_background_color: "Uses the selected accent color as the active card background.",
  ulm_card_media_player_color: "Accent color used for active media-player controls.",
  ulm_card_generic_color: "Accent color used while the generic entity is active.",
  ulm_card_generic_force_background_color: "Fills the generic card with its accent color while active.",
  ulm_card_generic_swap_color: "Accent color used by the swapped generic layout.",
  ulm_card_generic_swap_force_background_color: "Fills the swapped generic card with its accent color while active.",
  ulm_card_graph_color: "Line and fill color used for the primary history series.",
  ulm_card_graph_color2: "Line color used for the optional secondary history series.",
  ulm_card_graph_entity2: "Optional second entity plotted alongside the primary entity.",
  ulm_card_graph_group_by: "Source-compatible mini-graph grouping mode.",
  ulm_card_graph_hours: "Number of recent history hours represented by the graph.",
  ulm_card_graph_icon_color: "Optional accent color for the graph header icon.",
  ulm_card_graph_line_width: "Stroke width used by the history line.",
  ulm_card_graph_points: "Source-compatible number of graph samples per hour.",
  ulm_card_graph_type: "Choose the source fill, line, or bar presentation.",
  ulm_card_navigate_color: "Accent color used by the navigation icon.",
  ulm_card_thermostat_enable_collapse: "Hides expanded controls while the thermostat is off.",
  ulm_card_thermostat_enable_controls: "Adds buttons for changing the configured temperature setpoint.",
  ulm_card_thermostat_enable_hvac_modes: "Shows buttons for the HVAC modes supported by the climate entity.",
  ulm_card_thermostat_enable_background_color: "Uses the active HVAC mode color for the card background.",
  ulm_card_thermostat_enable_display_temperature: "Displays the current temperature beside the setpoint.",
  ulm_card_thermostat_enable_horizontal: "Places thermostat content and controls in the upstream horizontal arrangement.",
  ulm_card_cover_enable_slider: "Lets you set the cover position directly from the card.",
  ulm_card_cover_color: "Accent used while the cover is open or moving.",
  ulm_card_cover_display_left_right: "Uses left and right arrows for horizontally moving covers.",
  ulm_card_cover_enable_controls: "Adds close, stop, open, and optional favorite-position buttons.",
  ulm_card_cover_enable_horizontal: "Places the summary and one control region side by side.",
  ulm_card_cover_enable_tilt: "Adds close, stop, and open tilt controls.",
  ulm_card_cover_favorite_percentage: "Adds a star button that moves the cover to this percentage.",
  ulm_card_cover_force_background_color: "Uses the cover accent as the card background while active.",
  ulm_card_cover_garage_large: "Uses the garage variant icons for large garage doors.",
  ulm_card_cover_icon: "Optional icon override; otherwise the icon follows device class and state.",
  ulm_card_cover_invert_percent: "Inverts the displayed cover percentage and active coloring.",
  ulm_card_cover_name: "Optional source-compatible name override.",
  ulm_card_cover_show_last_changed: "Shows the entity's last-changed timestamp instead of its state.",
  ulm_card_invert_percent: "Legacy alias for inverted cover percentage behavior.",
  ulm_card_cover_slider_min: "Lowest position percentage available on the slider.",
  ulm_card_cover_slider_max: "Highest position percentage available on the slider.",
  ulm_card_fan_enable_slider: "Lets you set fan speed directly from the card.",
  ulm_card_fan_slider_min: "Lowest fan speed percentage available on the slider.",
  ulm_card_fan_slider_max: "Highest fan speed percentage available on the slider.",
  ulm_card_fan_enable_button: "Adds a button that toggles fan oscillation.",
  ulm_card_fan_button_icon: "Icon displayed on the oscillation button.",
  ulm_card_fan_button_service: "Home Assistant domain.service called by the fan option button.",
  ulm_card_fan_color: "Accent used while the fan is on.",
  ulm_card_fan_enable_collapse: "Hides the slider and option button while the fan is off.",
  ulm_card_fan_enable_horizontal: "Places the fan summary and controls side by side.",
  ulm_card_fan_force_background_color: "Uses the fan accent as the card background while active.",
  ulm_card_fan_hum_attribute: "Entity attribute whose numeric value is shown as humidity.",
  ulm_card_fan_icon: "Optional source-compatible fan icon override.",
  ulm_card_fan_name: "Optional source-compatible fan name override.",
  ulm_card_fan_oscillate_attribute: "Boolean entity attribute read to determine the next oscillation value.",
  ulm_card_fan_temp_attribute: "Entity attribute whose numeric value is shown as temperature.",
  ulm_card_binary_sensor_color: "Accent used while the binary sensor is active.",
  ulm_card_binary_sensor_force_background_color: "Uses the sensor accent as the card background while active.",
  ulm_card_binary_sensor_icon: "Optional source-compatible binary sensor icon override.",
  ulm_card_binary_sensor_name: "Optional source-compatible binary sensor name override.",
  ulm_card_binary_sensor_show_last_changed: "Displays how long ago the sensor changed state.",
  ulm_card_binary_sensor_alert_color: "Accent used while the alert sensor is active.",
  ulm_card_binary_sensor_alert_force_background_color: "Uses the alert accent as the card background while active.",
  ulm_card_binary_sensor_alert_icon: "Optional source-compatible alert icon override.",
  ulm_card_binary_sensor_alert_name: "Optional source-compatible alert name override.",
  ulm_card_binary_sensor_alert_show_last_changed: "Displays how long ago the alert changed state.",
  ulm_card_input_boolean_color: "Accent used while the helper is on.",
  ulm_card_input_boolean_force_background_color: "Uses the helper accent as the card background while on.",
  ulm_card_input_boolean_icon: "Optional source-compatible input boolean icon override.",
  ulm_card_input_boolean_name: "Optional source-compatible input boolean name override.",
  ulm_custom_card_bar_card_color: "Color used for the filled portion of the horizontal bar.",
  ulm_custom_card_bar_card_icon: "Optional icon override for the circular header icon.",
  ulm_custom_card_bar_card_icon_color: "Optional accent color for the header icon and its circle.",
  ulm_custom_card_bar_card_indicator: "Shows the current-value indicator at the leading edge of the bar.",
  ulm_custom_card_bar_card_max: "Entity value represented by a completely filled bar.",
  ulm_custom_card_bar_card_min: "Entity value represented by an empty bar.",
  ulm_custom_card_bar_card_name: "Optional name displayed below the current value.",
  ulm_custom_card_bar_card_show_icon: "Shows or hides the complete icon and text header above the bar.",
  ulm_custom_card_bar_card_value: "Displays the entity value at the right side of the bar.",
  ulm_custom_card_washer_power: "Sensor used to show the washer's current power consumption.",
  ulm_custom_card_washer_remote_control: "Entity whose true or on state exposes remote washer controls.",
  ulm_custom_card_washer_machine_state: "Entity containing the washer run, pause, or stopped state.",
  ulm_custom_card_washer_machine_stop_state: "Exact machine-state value that means the washer is stopped.",
  ulm_custom_card_washer_job_state: "Entity containing the active configured program stage.",
  ulm_custom_card_washer_job_progress: "Percentage entity shown in the washer progress bar.",
  ulm_custom_card_washer_job_states: "Up to 5 named program stages with their Material Design icons.",
  ulm_custom_card_washer_delayed_start: "Input boolean toggled by the delayed-start control.",
  ulm_custom_card_washer_delayed_starttime: "Input datetime adjusted by the delayed-start controls.",
  ulm_custom_card_washer_label_idle: "Text shown while the machine is idle or off.",
  ulm_custom_card_washer_label_configuring: "Text shown while delayed start is being configured.",
  ulm_custom_card_washer_label_running: "Text shown while the machine is running.",
  ulm_custom_card_washer_start_action: "Home Assistant action emitted by the start control.",
  ulm_custom_card_washer_pause_action: "Home Assistant action emitted by the pause control.",
  ulm_custom_card_washer_stop_action: "Home Assistant action emitted by the stop control.",
  power_entity: "Entity used for the source-specific power readout.",
  door_entity: "Entity used for the washer door status.",
  finished_entity: "Entity used for the washer program-finished status.",
  battery_state_entity: "Entity used to detect whether the battery is charging.",
  charger_type_entity: "Optional entity containing the active charger type.",
  secondary_entity: "Optional secondary entity used when primary media metadata is incomplete.",
  darkMode: "Uses the dark palette documented by the upstream Sun Card.",
  language: "Locale used by source-specific labels and time formatting.",
  showAzimuth: "Shows the current solar azimuth below the sun arc.",
  showElevation: "Shows the current solar elevation below the sun arc.",
  timeFormat: "Chooses 12-hour or 24-hour source time formatting.",
  title: "Optional title shown above the source-specific card.",
  ulm_custom_card_iAbadia_battery_chip_entity: "Battery entity targeted by the chip and its more-info action.",
  ulm_custom_card_iAbadia_battery_chip_icon: "Optional icon replacing the default battery glyph.",
  ulm_custom_card_iAbadia_battery_chip_warning: "Battery level at or below which the chip becomes yellow.",
  ulm_custom_card_iAbadia_battery_chip_danger: "Battery level at or below which the chip becomes red.",
  ulm_custom_card_imswel_medias_index: "One-based item index read from the media entity data attribute.",
  ulm_custom_card_imswel_medias_platform: "Selects Plex library, Radarr upcoming, or Sonarr upcoming semantics.",
  ulm_card_homeassistant_entity: "Optional overall update-status entity used by legacy configurations.",
  ulm_card_homeassistant_core: "Update, sensor, or binary sensor containing installed and latest Core versions.",
  ulm_card_homeassistant_supervisor: "Update, sensor, or binary sensor containing installed and latest Supervisor versions.",
  ulm_card_homeassistant_os: "Update, sensor, or binary sensor containing installed and latest Home Assistant OS versions.",
  tablet_button_usb_entity: "Switch or helper toggled by the green USB control.",
  tablet_button_motion_entity: "Motion or presence entity toggled by the green motion control.",
  tablet_button_display_entity: "Switch or helper toggled by the green display control.",
  tablet_restart_entity: "Button entity pressed by the blue restart control.",
  tablet_maintenance_entity: "Switch or helper toggled by the orange maintenance control.",
  tablet_reload_entity: "Button entity pressed by the blue reload control.",
  tablet_ram_entity: "Sensor shown in the centered RAM metric.",
  tablet_disk_entity: "Sensor shown in the centered Disk metric.",
  tablet_power_entity: "Entity shown in the centered Power metric.",
  ulm_card_person_entity: "Person shown by this card.",
  ulm_card_person_use_entity_picture: "Uses the person's entity picture instead of the configured face icon.",
  ulm_card_person_zone1: "Zone entity used for the first custom location badge.",
  ulm_card_person_zone2: "Zone entity used for the second custom location badge.",
  ulm_address: "Sensor whose state is shown as the current address.",
  ulm_address_locality: "Sensor whose Locality attribute is shown as the current location.",
  ulm_card_person_driving_entity: "Binary sensor that changes the badge and label while driving.",
  ulm_card_person_battery_entity: "Sensor containing the person's device battery percentage.",
  ulm_card_person_battery_state_entity: "Sensor whose state indicates whether the battery is charging.",
  ulm_card_person_commute_entity: "Sensor containing commute time in minutes.",
  ulm_card_person_cummute_icon: "Icon shown beside the commute time.",
  ulm_multiline: "Places battery and commute details on a separate row.",
  energy_entity: "Optional sensor containing the outlet's accumulated energy consumption.",
  black_entity: "Sensor containing the remaining black toner percentage.",
  yellow_entity: "Sensor containing the remaining yellow toner percentage.",
  magenta_entity: "Sensor containing the remaining magenta toner percentage.",
  cyan_entity: "Sensor containing the remaining cyan toner percentage.",
  minimum: "Lowest value represented by the gauge.",
  maximum: "Highest value represented by the gauge.",
  ulm_card_light_colorpick_name: "Name displayed in the light header.",
  ulm_card_light_colorpick_transition: "Transition time, in seconds, sent with each color selection.",
};

export const editorHelper = (key: string): string | undefined => helpers[key];
