import type { CatalogItem } from "./types";

export const isRemovedPopupOption = (name: string): boolean =>
  /popup|browser_mod/i.test(name);

const supportedByFamily: Record<string, readonly string[]> = {
  weather: [
    "ulm_card_weather_backdrop",
    "ulm_card_weather_primary_info",
    "ulm_card_weather_secondary_info",
  ],
  light: [
    "ulm_card_light_enable_slider",
    "ulm_card_light_enable_slider_minSet",
    "ulm_card_light_enable_slider_maxSet",
    "ulm_card_light_enable_collapse",
    "ulm_card_light_enable_horizontal",
    "ulm_card_light_enable_color",
    "ulm_card_light_force_background_color",
    "ulm_card_light_enable_buttons",
    "ulm_card_light_brightness_low",
    "ulm_card_light_brightness_medium",
    "ulm_card_light_brightness_high",
    "ulm_card_light_enable_horizontal_wide",
    "ulm_card_light_color",
  ],
  battery: [
    "ulm_card_battery_attribute",
    "ulm_card_battery_battery_state_entity_id",
    "ulm_card_battery_charger_type_entity_id",
    "ulm_card_battery_battery_level_danger",
    "ulm_card_battery_battery_level_warning",
    "ulm_card_battery_charging_animation",
    "ulm_card_battery_color_battery_level_danger",
    "ulm_card_battery_color_battery_level_warning",
    "ulm_card_battery_color_battery_level_ok",
    "ulm_card_battery_name",
  ],
  media: [
    "ulm_card_media_player_enable_art",
    "ulm_card_media_player_enable_controls",
    "ulm_card_media_player_enable_volume_slider",
    "ulm_card_media_player_enable_volume_buttons",
    "ulm_card_media_player_enable_volume_adjust",
    "ulm_card_media_player_collapsible",
    "ulm_card_media_player_idle_off",
    "ulm_card_media_player_player_controls_entity",
    "ulm_card_media_player_more_info",
    "ulm_card_media_player_power_button",
    "ulm_card_media_player_force_background_color",
    "ulm_card_media_player_color",
  ],
  cover: [
    "ulm_card_cover_color",
    "ulm_card_cover_display_left_right",
    "ulm_card_cover_enable_controls",
    "ulm_card_cover_enable_horizontal",
    "ulm_card_cover_enable_slider",
    "ulm_card_cover_enable_tilt",
    "ulm_card_cover_favorite_percentage",
    "ulm_card_cover_force_background_color",
    "ulm_card_cover_garage_large",
    "ulm_card_cover_icon",
    "ulm_card_cover_invert_percent",
    "ulm_card_cover_name",
    "ulm_card_cover_show_last_changed",
    "ulm_card_cover_slider_min",
    "ulm_card_cover_slider_max",
    "ulm_card_invert_percent",
  ],
  control: [
    "ulm_card_fan_button_service",
    "ulm_card_fan_color",
    "ulm_card_fan_enable_collapse",
    "ulm_card_fan_enable_horizontal",
    "ulm_card_fan_enable_slider",
    "ulm_card_fan_slider_min",
    "ulm_card_fan_slider_max",
    "ulm_card_fan_enable_button",
    "ulm_card_fan_button_icon",
    "ulm_card_fan_force_background_color",
    "ulm_card_fan_hum_attribute",
    "ulm_card_fan_icon",
    "ulm_card_fan_name",
    "ulm_card_fan_oscillate_attribute",
    "ulm_card_fan_temp_attribute",
  ],
};

const supportedByItem: Record<string, readonly string[]> = {
  card_generic: [
    "ulm_card_generic_color",
    "ulm_card_generic_force_background_color",
    "ulm_card_generic_swap_color",
    "ulm_card_generic_swap_force_background_color",
  ],
  card_graph: [
    "ulm_card_graph_color",
    "ulm_card_graph_color2",
    "ulm_card_graph_entity2",
    "ulm_card_graph_group_by",
    "ulm_card_graph_hours",
    "ulm_card_graph_icon_color",
    "ulm_card_graph_line_width",
    "ulm_card_graph_points",
    "ulm_card_graph_type",
  ],
  card_navigate: [
    "ulm_card_navigate_color",
  ],
  card_binary_sensor: [
    "ulm_card_binary_sensor_color",
    "ulm_card_binary_sensor_force_background_color",
    "ulm_card_binary_sensor_icon",
    "ulm_card_binary_sensor_name",
    "ulm_card_binary_sensor_show_last_changed",
  ],
  card_binary_sensor_alert: [
    "ulm_card_binary_sensor_alert_color",
    "ulm_card_binary_sensor_alert_force_background_color",
    "ulm_card_binary_sensor_alert_icon",
    "ulm_card_binary_sensor_alert_name",
    "ulm_card_binary_sensor_alert_show_last_changed",
  ],
  card_input_boolean: [
    "ulm_card_input_boolean_color",
    "ulm_card_input_boolean_force_background_color",
    "ulm_card_input_boolean_icon",
    "ulm_card_input_boolean_name",
  ],
  custom_card_bar_card: [
    "ulm_custom_card_bar_card_color",
    "ulm_custom_card_bar_card_icon",
    "ulm_custom_card_bar_card_icon_color",
    "ulm_custom_card_bar_card_indicator",
    "ulm_custom_card_bar_card_max",
    "ulm_custom_card_bar_card_min",
    "ulm_custom_card_bar_card_name",
    "ulm_custom_card_bar_card_show_icon",
    "ulm_custom_card_bar_card_value",
  ],
  custom_card_haven_washer: [
    "ulm_custom_card_washer_power",
    "ulm_custom_card_washer_remote_control",
    "ulm_custom_card_washer_machine_state",
    "ulm_custom_card_washer_machine_stop_state",
    "ulm_custom_card_washer_job_state",
    "ulm_custom_card_washer_job_progress",
    "ulm_custom_card_washer_job_states",
    "ulm_custom_card_washer_delayed_start",
    "ulm_custom_card_washer_delayed_starttime",
    "ulm_custom_card_washer_label_idle",
    "ulm_custom_card_washer_label_configuring",
    "ulm_custom_card_washer_label_running",
    "ulm_custom_card_washer_start_action",
    "ulm_custom_card_washer_pause_action",
    "ulm_custom_card_washer_stop_action",
  ],
  custom_card_httpedo13_sun: [
    "darkMode",
    "language",
    "showAzimuth",
    "showElevation",
    "timeFormat",
    "title",
  ],
  custom_card_iAbadia_battery_chip: [
    "ulm_custom_card_iAbadia_battery_chip_entity",
    "ulm_custom_card_iAbadia_battery_chip_icon",
    "ulm_custom_card_iAbadia_battery_chip_danger",
    "ulm_custom_card_iAbadia_battery_chip_warning",
  ],
  custom_card_imswel_medias: [
    "ulm_custom_card_imswel_medias_index",
    "ulm_custom_card_imswel_medias_platform",
  ],
};

export const supportedUpstreamOption = (item: CatalogItem, name: string): boolean =>
  !isRemovedPopupOption(name) && (
    [item.upstreamId, ...(item.sourceIds ?? [])].some((id) => supportedByItem[id]?.includes(name) === true) ||
    supportedByFamily[item.family]?.includes(name) === true
  );
