import {
  publicItemForSource,
  UPSTREAM_CATALOG,
  variantForSource,
} from "./catalog";

export type VisualAuditStatus = "pending" | "accepted" | "deviation";

export interface VisualAuditEntry {
  sourceId: string;
  publicId: string;
  variant?: string;
  category: "default-card" | "custom-card";
  rendererId: string;
  compositionId: string;
  sourcePath: string;
  referenceScreenshot?: string;
  fixturePath: string;
  fixtureId: string;
  artifactPath?: string;
  themes: readonly ("light" | "dark")[];
  widths: readonly number[];
  requiredRegions: readonly string[];
  forbiddenRegions: readonly string[];
  status: VisualAuditStatus;
  pickerAccepted: boolean;
  editorAccepted: boolean;
  visualAccepted: boolean;
  statesAccepted: boolean;
  interactionsAccepted: boolean;
  liveAccepted: boolean;
  inspectedAt?: string;
  reviewerNotes: readonly string[];
  deviations: readonly string[];
}

const defaultReferences: Record<string, string> = {
  card_battery: "card_battery.png",
  card_binary_sensor: "card_binary_sensor.png",
  card_binary_sensor_alert: "card_binary_sensor_alert.png",
  card_cover: "card_cover_controls.png",
  card_fan: "card_fan_slider.png",
  card_generic: "card_generic.png",
  card_generic_swap: "card_generic_swap.png",
  card_graph: "card_graph.png",
  card_input_boolean: "card_input_boolean.png",
  card_light: "card_light_combi.png",
  card_media_player: "card_media_player_art_controls.png",
  card_navigate: "card_navigate.png",
  card_person: "card_person.png",
  card_power_outlet: "card_power_outlet.png",
  card_room: "room-card.png",
  card_scenes: "card_scenes.png",
  card_script: "card_script.png",
  card_thermostat: "card_thermostat_with_controls.png",
  card_title: "card_title.png",
  card_vacuum: "card_vacuum_cleaning.png",
  card_vertical_button: "card_example.png",
  card_weather: "card_weather.png",
  card_weather_ulm: "card_weather_ulm.png",
  card_welcome_scenes: "card_welcome_scenes.png",
};

const defaultStructures: Record<string, { required: string[]; forbidden: string[] }> = {
  card_battery: { required: ["ulm-default-battery", "value-first"], forbidden: ["battery-track", "sparkline"] },
  card_binary_sensor: { required: ["ulm-binary", "ulm-icon"], forbidden: ["sparkline", "ulm-controls"] },
  card_binary_sensor_alert: { required: ["ulm-binary", "variant-alert"], forbidden: ["sparkline", "ulm-controls"] },
  card_cover: { required: ["ulm-cover", "cover-controls"], forbidden: ["sparkline"] },
  card_fan: { required: ["ulm-fan", "ulm-fan-slider"], forbidden: ["sparkline"] },
  card_generic: { required: ["value-first", "ulm-icon"], forbidden: ["sparkline", "ulm-controls"] },
  card_generic_swap: { required: ["ulm-generic-swap", "value-first"], forbidden: ["sparkline", "ulm-controls"] },
  card_graph: { required: ["ulm-default-graph", "sparkline", "is-filled"], forbidden: ["ulm-light-slider"] },
  card_input_boolean: { required: ["ulm-simple-default", "ulm-icon"], forbidden: ["sparkline", "ulm-controls"] },
  card_light: { required: ["ulm-light-card", "ulm-light-slider"], forbidden: ["sparkline"] },
  card_media_player: { required: ["ulm-media", "media-art", "ulm-controls"], forbidden: ["sparkline"] },
  card_navigate: { required: ["ulm-default-navigation", "ulm-icon"], forbidden: ["sparkline", "weather-forecast"] },
  card_person: { required: ["ulm-person", "presence-dot"], forbidden: ["sparkline", "ulm-controls"] },
  card_power_outlet: { required: ["ulm-simple-default", "ulm-icon"], forbidden: ["sparkline", "ulm-controls"] },
  card_room: { required: ["ulm-room", "room-main", "room-sensor"], forbidden: ["sparkline", "scene-grid"] },
  card_scenes: { required: ["scene-pills", "scene-grid", "scene-button"], forbidden: ["sparkline", "room-main"] },
  card_script: { required: ["ulm-simple-default", "ulm-icon"], forbidden: ["sparkline", "ulm-controls"] },
  card_thermostat: { required: ["ulm-climate", "climate-target"], forbidden: ["sparkline"] },
  card_title: { required: ["ulm-title", "ulm-copy"], forbidden: ["ulm-icon", "sparkline"] },
  card_vacuum: { required: ["ulm-default-vacuum", "vacuum-actions"], forbidden: ["sparkline"] },
  card_vertical_button: { required: ["ulm-vertical-button", "ulm-icon"], forbidden: ["sparkline"] },
  card_weather: { required: ["legacy-weather", "legacy-weather-current", "legacy-weather-details"], forbidden: ["ulm-light-slider"] },
  card_weather_ulm: { required: ["ulm-weather", "weather-metrics"], forbidden: ["legacy-weather", "ulm-light-slider"] },
  card_welcome_scenes: { required: ["welcome-scenes", "welcome-toolbar", "scene-grid"], forbidden: ["sparkline", "room-main"] },
};

const acceptedDefaults = Object.fromEntries(Object.entries(defaultStructures).map(([sourceId, structure]) => [
  sourceId,
  {
    compositionId: `default:${sourceId}:${structure.required[0]}`,
    referenceScreenshot: `.tmp-ui-minimalist/docs/assets/img/ulm_cards/${defaultReferences[sourceId]}`,
    fixturePath: "demo/default-card-comparison.html",
    artifactPath: `docs/assets/visual-audit/${sourceId}-comparison.png`,
    themes: ["light"],
    widths: [320],
    requiredRegions: structure.required,
    forbiddenRegions: structure.forbidden,
    status: "accepted",
    inspectedAt: "2026-09-23",
    deviations: [
      "The standalone fixture abbreviates MDI glyphs; Home Assistant renders the configured icons.",
    ],
  } satisfies Partial<VisualAuditEntry>,
]));

const customStructures: Record<string, string[]> = {
  custom_card_afvalophaling: ["custom-waste-card", "waste-grid"],
  custom_card_alarm_time: ["custom-alarm-time", "alarm-time-controls"],
  custom_card_apexcharts: ["custom-apexcharts", "apex-chart"],
  custom_card_camera: ["ulm-camera", "camera-caption"],
  custom_card_chromecast: ["custom-chromecast", "chromecast-controls"],
  custom_card_damix48_power_details: ["custom-power-details", "power-details-chart"],
  custom_card_device_tracker: ["custom-device-tracker", "device-tracker-icon"],
  custom_card_drealine_roomview: ["custom-room-view", "room-view-actions"],
  custom_card_eraycetinay_elapsed_time: ["custom-elapsed-time", "ulm-label"],
  custom_card_eraycetinay_lock: ["custom-eray-lock", "eray-lock-icon"],
  custom_card_esh_room: ["ulm-room", "room-main"],
  custom_card_esh_welcome: ["custom-esh-welcome", "esh-welcome-items"],
  custom_card_haven_washer: ["custom-washer", "washer-stages"],
  custom_card_heat_pump: ["custom-heat-pump", "heat-pump-modes"],
  custom_card_homeassistant_updates: ["custom-ha-updates", "ha-update-list"],
  custom_card_httpedo13_sun: ["custom-sun-card", "sun-arc"],
  custom_card_httpedo13_thermostat: ["custom-compact-thermostat", "compact-thermostat-controls"],
  custom_card_iAbadia_battery_chip: ["custom-battery-chip"],
  custom_card_imswel_medias: ["custom-media-library", "media-library-overlay"],
  custom_card_imswel_person: ["custom-imswel-person", "imswel-person-trackers"],
  custom_card_input_datetime: ["custom-input-datetime", "input-datetime-controls"],
  custom_card_input_number: ["custom-input-number", "input-number-controls"],
  custom_card_irmajavi_entities: ["custom-irmajavi-entities", "irmajavi-four"],
  custom_card_irmajavi_speedtest: ["custom-irmajavi-speedtest", "speedtest-metrics"],
  custom_card_irmajavi_weather: ["custom-irmajavi-weather", "irmajavi-weather-header"],
  custom_card_light_colorpick: ["custom-light-colorpick", "light-color-swatches"],
  custom_card_media_player_sonos: ["custom-sonos", "sonos-controls"],
  custom_card_more_power_outlet: ["custom-more-power-outlet"],
  custom_card_mpse_gauge: ["custom-dual-gauge", "dual-gauge"],
  custom_card_mpse_printer: ["custom-mpse-printer", "toner-bars"],
  custom_card_mpse_thermostat: ["custom-compact-thermostat", "compact-thermostat-controls"],
  custom_card_mpse_wifisignal: ["custom-wifi-signal"],
  custom_card_nas: ["custom-nas-info"],
  custom_card_neekster_update: ["custom-neekster-update", "custom-card-heading"],
  custom_card_nik_clock: ["custom-nik-clock"],
  custom_card_nik_door: ["custom-nik-door", "nik-door-controls"],
  custom_card_nik_nas: ["custom-nik-nas", "nik-nas-metrics"],
  custom_card_nik_tablet: ["custom-nik-tablet", "tablet-status-row"],
  custom_card_paddy_dwd_pollen: ["custom-paddy-pollen", "pollen-icon"],
  custom_card_paddy_waste_collection: ["custom-paddy-waste", "paddy-waste-icon"],
  custom_card_paddy_welcome: ["custom-paddy-welcome"],
  custom_card_person_chip: ["custom-person-chip"],
  custom_card_person_info: ["custom-person-info", "person-info-details"],
  custom_card_person_info_small: ["custom-person-info-small", "is-compact"],
  custom_card_playstation: ["custom-console-card", "console-content"],
  custom_card_qubino: ["custom-qubino"],
  custom_card_ristou_person: ["custom-ristou-person", "ristou-person-main"],
  custom_card_saxel_fan: ["custom-saxel-fan", "fan-speed-row"],
  custom_card_scenes: ["ulm-scenes", "scene-grid"],
  custom_card_schumijo_car: ["custom-schumijo-car", "car-metrics"],
  custom_card_schumijo_flower: ["custom-schumijo-flower", "flower-metrics"],
  custom_card_senoro_win: ["custom-senoro-window", "window-battery"],
  custom_card_sisimomo_printer: ["custom-sisimomo-printer", "printer-cartridges"],
  custom_card_speedtest_shogun160: ["custom-speedtest-shogun", "speedtest-three"],
  custom_card_tpx01_aircondition: ["custom-tpx-aircondition", "aircondition-controls"],
  custom_card_vncntdev_device_tracer: ["custom-device-tracer", "device-tracer-meta"],
  custom_card_water_heater: ["custom-water-heater", "water-heater-controls"],
  custom_card_wilbiev_subtitle: ["ulm-title", "variant-divider-subtitle"],
  custom_card_wilbiev_title: ["ulm-title", "variant-divider-title"],
  custom_card_wsly_pollen: ["custom-wsly-pollen"],
  custom_card_yagrasdemonde_lights_count: ["custom-lights-count"],
};

const customReferences: Record<string, string> = {
  custom_card_afvalophaling: "custom_card_afvalophaling_1.png",
  custom_card_apexcharts: "custom_card_apexcharts_line.png",
  custom_card_camera: "screenshot_custom_camera1.png",
  custom_card_damix48_power_details: "custom_power_details.png",
  custom_card_device_tracker: "custom_card_device_tracker.png",
  custom_card_drealine_roomview: "custom_card_drealine_roomview_1.png",
  custom_card_eraycetinay_elapsed_time: "custom_card_eraycetinay_elapsed_time.png",
  custom_card_eraycetinay_lock: "custom_card_eraycetinay_lock.png",
  custom_card_esh_room: "custom_card_esh_room_light.png",
  custom_card_esh_welcome: "custom_card_esh_welcome_light.png",
  custom_card_haven_washer: "custom_card_haven_washer_running.png",
  custom_card_heat_pump: "Heat_pump.PNG",
  custom_card_homeassistant_updates: "ulm_cards/card_homeassistant_updates.png",
  custom_card_httpedo13_sun: "sun-card.png",
  custom_card_httpedo13_thermostat: "thermostat_white_with_heating_ui.png",
  custom_card_iAbadia_battery_chip: "custom_card_iAbadia_battery_chip.png",
  custom_card_imswel_person: "custom_card_imswel_person.gif",
  custom_card_input_datetime: "card_input_datetime.png",
  custom_card_input_number: "card_input_number.png",
  custom_card_irmajavi_entities: "screenshot_irmajavi_entities_card.jpg",
  custom_card_irmajavi_speedtest: "screenshot_irmajavi_speedtest_card.jpg",
  custom_card_irmajavi_weather: "screenshot_irmajavi_weather_card.jpg",
  custom_card_media_player_sonos: "media_player_sonos.png",
  custom_card_mpse_gauge: "custom_gauge.png",
  custom_card_mpse_printer: "custom_printer.png",
  custom_card_mpse_thermostat: "custom_thermostat.png",
  custom_card_mpse_wifisignal: "custom_wifisignal.png",
  custom_card_nas: "custom_card_nas.png",
  custom_card_neekster_update: "custom_card_neekster_update.png",
  custom_card_nik_clock: "custom_card_nik_clock.png",
  custom_card_nik_door: "custom_card_nik_door.png",
  custom_card_nik_nas: "custom_card_nik_nas_on.png",
  custom_card_nik_tablet: "custom_card_nik_tablet_1.png",
  custom_card_person_info: "custom_card_person_info.png",
  custom_card_person_info_small: "custom_card_person_info_small_light.png",
  custom_card_ristou_person: "custom_card_ristou_person/custom_card_ristou_person_light.png",
  custom_card_saxel_fan: "custom_fan_light_theme.png",
  custom_card_scenes: "card_scenes.png",
  custom_card_schumijo_car: "car.png",
  custom_card_schumijo_flower: "flower.png",
  custom_card_senoro_win: "senoro_win_card.png",
  custom_card_sisimomo_printer: "custom_card_sisimomo_printer.png",
  custom_card_vncntdev_device_tracer: "custom_device_tracer.jpg",
  custom_card_wilbiev_subtitle: "custom_card_wilbiev_subtitle.png",
  custom_card_wilbiev_title: "custom_card_wilbiev_title.png",
  custom_card_wsly_pollen: "custom_card_wsly_pollen_light.png",
  custom_card_yagrasdemonde_lights_count: "screenshot_light_count_lights.png",
};

const acceptedCustoms = Object.fromEntries(Object.entries(customStructures).map(([sourceId, requiredRegions]) => [
  sourceId,
  {
    compositionId: `custom:${sourceId}:${requiredRegions[0]}`,
    referenceScreenshot: `.tmp-ui-minimalist/docs/assets/img/${customReferences[sourceId] ?? "cards.png"}`,
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-cards-complete-comparison.png",
    themes: ["light"],
    widths: [320],
    requiredRegions,
    forbiddenRegions: ["ulm-metric", "ulm-detail-card", "ulm-device-status", "ulm-schedule-card", "ulm-helper-card"],
    status: "accepted",
    inspectedAt: "2026-09-23",
    deviations: customReferences[sourceId]
      ? ["The standalone fixture abbreviates MDI glyphs; Home Assistant renders the configured icons."]
      : ["No dedicated upstream screenshot exists; composition was checked against the pinned YAML structure and documentation variables."],
  } satisfies Partial<VisualAuditEntry>,
]));

const accepted: Record<string, Partial<VisualAuditEntry>> = {
  ...acceptedDefaults,
  ...acceptedCustoms,
  custom_card_afvalophaling: {
    compositionId: "custom:custom_card_afvalophaling:semantic-waste-streams",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/ulm_cards/custom_card_afvalophaling_1.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-afvalophaling-full-comparison.png",
    themes: ["light"],
    widths: [320],
    requiredRegions: ["custom-waste-card", "waste-grid", "waste-row"],
    forbiddenRegions: ["ulm-metric", "sparkline", "ulm-schedule-card"],
    status: "accepted",
    inspectedAt: "2026-09-23",
    deviations: [
      "The standalone fixture abbreviates MDI glyphs; Home Assistant renders the configured icons.",
      "Full and partial stream sizing were inspected; the partial artifact is docs/assets/visual-audit/custom-card-afvalophaling-partial-comparison.png.",
    ],
  },
  custom_card_bar_card: {
    compositionId: "bar-card:compact-header-progress",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/screenshot_bar_card.png",
    fixturePath: "demo/bar-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-bar-card-comparison.png",
    themes: ["dark"],
    widths: [237],
    requiredRegions: [
      "minimalist-bar-card",
      "bar-card-header",
      "bar-card-icon",
      "bar-card-primary-value",
      "bar-card-name",
      "bar-card-track",
      "bar-card-fill",
    ],
    forbiddenRegions: ["sparkline", "metric-extremes", "ulm-metric"],
    status: "accepted",
    inspectedAt: "2026-09-23",
    deviations: [
      "The standalone comparison fixture uses abbreviated icon stubs; Home Assistant renders the configured MDI glyphs.",
    ],
  },
  custom_card_device_tracker: {
    compositionId: "custom:custom_card_device_tracker:dual-independent-trackers",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_device_tracker.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-device-tracker-batch-comparison.png",
    themes: ["dark"], widths: [320],
    requiredRegions: ["custom-device-tracker", "device-tracker-icon", "tracker-one", "tracker-two"],
    forbiddenRegions: ["generic-presence-tile", "sparkline"], deviations: [],
  },
  custom_card_drealine_roomview: {
    compositionId: "custom:custom_card_drealine_roomview:named-groups",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_drealine_roomview_1.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-drealine-roomview-batch-comparison.png",
    themes: ["light"], widths: [320],
    requiredRegions: ["custom-room-view", "room-view-summary", "room-view-status", "room-view-actions"],
    forbiddenRegions: ["generic-entities-array", "sparkline"], deviations: [],
  },
  custom_card_eraycetinay_elapsed_time: {
    compositionId: "custom:custom_card_eraycetinay_elapsed_time:source-time-format",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_eraycetinay_elapsed_time.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-eraycetinay-elapsed-time-batch-comparison.png",
    themes: ["light"], widths: [320],
    requiredRegions: ["custom-elapsed-time", "ulm-icon", "ulm-label"],
    forbiddenRegions: ["ulm-controls", "sparkline"], deviations: [],
  },
  custom_card_eraycetinay_lock: {
    compositionId: "custom:custom_card_eraycetinay_lock:lock-warnings",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_eraycetinay_lock.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-eraycetinay-lock-batch-comparison.png",
    themes: ["light"], widths: [320],
    requiredRegions: ["custom-eray-lock", "eray-lock-control", "eray-lock-icon"],
    forbiddenRegions: ["generic-security-card", "sparkline"], deviations: [],
  },
  custom_card_esh_room: {
    compositionId: "custom:custom_card_esh_room:semantic-room-slots",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_esh_room_light.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-esh-room-batch-comparison.png",
    themes: ["light"], widths: [320],
    requiredRegions: ["custom-esh-room", "esh-room-main", "esh-room-controls"],
    forbiddenRegions: ["room-sensor", "scene-grid", "sparkline"], deviations: [],
  },
  custom_card_esh_welcome: {
    compositionId: "custom:custom_card_esh_welcome:topbar-semantic-navigation",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_esh_welcome_light.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-esh-welcome-batch-comparison.png",
    themes: ["light"], widths: [420],
    requiredRegions: ["custom-esh-welcome", "esh-welcome-toolbar", "esh-welcome-items"],
    forbiddenRegions: ["scene-grid", "sparkline"], deviations: [],
  },
  custom_card_heat_pump: {
    compositionId: "custom:custom_card_heat_pump:source-controls",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/Heat_pump.PNG",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-heat-pump-comparison.png",
    themes: ["light"],
    widths: [475],
    requiredRegions: ["custom-heat-pump", "heat-pump-temperature", "heat-pump-modes", "heat-pump-mode"],
    forbiddenRegions: ["mode-letter", "text-mode-button", "sparkline"],
    deviations: [],
  },
  custom_card_homeassistant_updates: {
    compositionId: "custom:custom_card_homeassistant_updates:hero-actions",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/ulm_cards/card_homeassistant_updates.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-homeassistant-updates-comparison.png",
    themes: ["light"],
    widths: [650],
    requiredRegions: ["custom-ha-updates", "ha-updates-hero", "ha-update-list", "ha-update-actions"],
    forbiddenRegions: ["generic-update-row", "sparkline"],
    deviations: [
      "The settings control opens Home Assistant's dedicated update settings instead of the pinned template's Developer Tools YAML page.",
      "The update control safely opens the first available update entity instead of navigating to the dashboard or directly installing an update.",
    ],
  },
  custom_card_nik_nas: {
    compositionId: "custom:custom_card_nik_nas:tiles-metrics-rings",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_nik_nas_on.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-nik-nas-comparison.png",
    themes: ["light"],
    widths: [510],
    requiredRegions: ["custom-nik-nas", "nik-nas-top", "nik-nas-metrics", "nik-nas-rings"],
    forbiddenRegions: ["generic-donut", "sparkline"],
    deviations: [],
  },
  custom_card_nik_tablet: {
    compositionId: "custom:custom_card_nik_tablet:controls-metrics-battery",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_nik_tablet_1.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-nik-tablet-comparison.png",
    themes: ["light"],
    widths: [390],
    requiredRegions: ["custom-nik-tablet", "nik-tablet-controls", "nik-tablet-metrics", "nik-tablet-battery-bar"],
    forbiddenRegions: ["generic-device-row", "sparkline"],
    deviations: [],
  },
  custom_card_person_info: {
    compositionId: "custom:custom_card_person_info:full-person-details",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_person_info.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-person-info-comparison.png",
    themes: ["dark"],
    widths: [165],
    requiredRegions: ["custom-person-info", "person-info-avatar", "person-info-badge", "person-info-details"],
    forbiddenRegions: ["generic-presence-tile", "sparkline"],
    deviations: [],
  },
  custom_card_person_info_small: {
    compositionId: "custom:custom_card_person_info_small:compact-person-tile",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/custom_card_person_info_small_light.png",
    fixturePath: "demo/custom-card-comparison.html",
    artifactPath: "docs/assets/visual-audit/custom-card-person-info-small-comparison.png",
    themes: ["light"],
    widths: [155],
    requiredRegions: ["custom-person-info-small", "person-info-avatar", "person-info-badge", "person-info-small-battery"],
    forbiddenRegions: ["person-info-details", "generic-presence-tile", "sparkline"],
    deviations: [],
  },
  card_generic: {
    compositionId: "default:card_generic:state-name-row",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/ulm_cards/card_generic.png",
    fixturePath: "demo/default-rich-comparison.html",
    artifactPath: "docs/assets/visual-audit/card_generic-comparison.png",
    themes: ["light"],
    widths: [320],
    requiredRegions: ["ulm-generic", "value-first", "ulm-icon"],
    forbiddenRegions: ["sparkline", "ulm-controls"],
    deviations: [],
  },
  card_generic_swap: {
    compositionId: "default:card_generic_swap:name-state-row",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/ulm_cards/card_generic_swap.png",
    fixturePath: "demo/default-rich-comparison.html",
    artifactPath: "docs/assets/visual-audit/card_generic_swap-comparison.png",
    themes: ["light"],
    widths: [320],
    requiredRegions: ["ulm-generic-swap", "ulm-copy", "ulm-icon"],
    forbiddenRegions: ["value-first", "sparkline", "ulm-controls"],
    deviations: [],
  },
  card_graph: {
    compositionId: "default:card_graph:generic-header-filled-history",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/ulm_cards/card_graph.png",
    fixturePath: "demo/default-rich-comparison.html",
    artifactPath: "docs/assets/visual-audit/card_graph-comparison.png",
    themes: ["light"],
    widths: [320],
    requiredRegions: ["ulm-default-graph", "value-first", "sparkline", "is-filled"],
    forbiddenRegions: ["ulm-light-slider"],
    deviations: [
      "The renderer uses deterministic entity history (or deterministic preview samples) instead of mini-graph-card's recorder query and curve interpolation.",
    ],
  },
  card_light: {
    compositionId: "default:card_light:header-slider-presets",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/ulm_cards/card_light_combi.png",
    fixturePath: "demo/default-rich-comparison.html",
    artifactPath: "docs/assets/visual-audit/card_light-comparison.png",
    themes: ["light"],
    widths: [320],
    requiredRegions: ["ulm-light-card", "light-header", "ulm-light-slider"],
    forbiddenRegions: ["sparkline"],
    deviations: [
      "The renderer uses a native range input under the source-styled slider instead of the upstream custom:my-slider dependency.",
    ],
  },
  card_media_player: {
    compositionId: "default:card_media_player:artwork-metadata-controls",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/ulm_cards/card_media_player_art_controls.png",
    fixturePath: "demo/default-rich-comparison.html",
    artifactPath: "docs/assets/visual-audit/card_media_player-comparison.png",
    themes: ["light"],
    widths: [320],
    requiredRegions: ["ulm-media", "media-art", "media-summary", "media-controls"],
    forbiddenRegions: ["sparkline"],
    deviations: [
      "The deterministic fixture uses a local gradient artwork data URI rather than copying the copyrighted album artwork shown upstream.",
      "The fourth source-list control follows the pinned YAML even though the pinned documentation crop emphasizes the three transport controls.",
    ],
  },
  card_navigate: {
    compositionId: "default:card_navigate:icon-label",
    referenceScreenshot: ".tmp-ui-minimalist/docs/assets/img/ulm_cards/card_navigate.png",
    fixturePath: "demo/default-rich-comparison.html",
    artifactPath: "docs/assets/visual-audit/card_navigate-comparison.png",
    themes: ["light"],
    widths: [320],
    requiredRegions: ["ulm-default-navigation", "ulm-icon", "navigation-label"],
    forbiddenRegions: ["ulm-copy", "sparkline"],
    deviations: [],
  },
};

const manuallyReviewed: Record<string, Partial<VisualAuditEntry>> = {
  card_generic: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected at a matched 320px width against the pinned source crop with real @mdi/js paths.",
      "The source state-first hierarchy, friendly-name label, active styling options, picker defaults, editor round trip, state rendering, and exact card-surface more-info action are covered by tests/default-rich-certification.test.ts.",
      "The semantic picker prefers sensor.bedroom_temperature_2 when that prepared live entity is available.",
      "Live Home Assistant E2E was intentionally not claimed.",
    ],
  },
  card_generic_swap: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected at a matched 320px width; the previous incorrect state-first ordering is corrected to source name-first/state-second ordering.",
      "Variant picker exposure, swapped editor options, migration, state rendering, and exact card-surface more-info action are covered by tests/default-rich-certification.test.ts.",
      "The exact live swapped config uses sensor.cv_plug_power; the unified picker opens on the default variant before the user selects Swapped.",
      "Live Home Assistant E2E was intentionally not claimed.",
    ],
  },
  card_graph: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected at a matched 320px width against the pinned filled-history composition with real @mdi/js paths.",
      "Graph entity migration, source graph editor controls, available history states, deterministic preview history, and exact card-surface more-info action are covered by tests/default-rich-certification.test.ts.",
      "The semantic picker prefers sensor.cv_plug_power when that prepared live entity is available.",
      "Live Home Assistant E2E and recorder/statistics querying were intentionally not claimed.",
    ],
  },
  card_light: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected at a matched 320px width against the source slider composition with real @mdi/js paths.",
      "Source-default picker behavior, graphical editor controls, on/off/unavailable/collapsed states, card action, slider, and all three brightness presets pass exact payload assertions.",
      "The semantic picker prefers light.joris_iris_1 when that prepared live entity is available.",
      "Live Home Assistant E2E was intentionally not claimed.",
    ],
  },
  card_media_player: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected at a matched 320px width against the pinned artwork/control source design with real @mdi/js paths.",
      "Source-default picker behavior, dedicated media editor options, playing/off/collapsed states, artwork metadata, and all ten visible configured interactions pass exact action/service assertions.",
      "The semantic picker prefers media_player.office_joris_tv_2 when that prepared live entity is available.",
      "Live Home Assistant E2E was intentionally not claimed.",
    ],
  },
  card_navigate: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected at a matched 320px width against the pinned icon-plus-label source crop with real @mdi/js paths.",
      "Legacy title/icon/path migration, picker navigation defaults, graphical editor round trip, entity-free rendering, and the exact navigate action payload are covered by tests/default-rich-certification.test.ts.",
      "The picker default and exact live config navigate to /config/updates.",
      "Live Home Assistant E2E was intentionally not claimed.",
    ],
  },
  card_battery: {
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    status: "pending",
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused 320px side-by-side manually inspected against the pinned card_battery reference.",
      "The deterministic fixture uses real @mdi/js SVG paths and covers default, wireless charging, wired charging, warning, and danger states.",
      "Picker defaults, graphical editor round trip, attribute-based levels, linked charging entities, thresholds, colors, and all card-surface actions pass tests/default-controls-certification.test.ts.",
      "Prepared live mappings are Yvette battery level with Joris battery level as the low-battery alternate; live verification remains intentionally unaccepted.",
    ],
    deviations: [
      "The Lit implementation keeps a 66px accessible touch target, so its cards are taller than the documentation montage.",
    ],
  },
  card_binary_sensor: {
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    status: "pending",
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused 320px active/inactive comparison manually inspected against the pinned card_binary_sensor reference.",
      "The fixture uses real MDI SVG paths and preserves the source icon, name, translated state, active accent, optional background, and last-changed behavior.",
      "Picker variant exposure, graphical editor round trip, state rendering, and all card-surface actions pass tests/default-controls-certification.test.ts.",
      "Prepared live mapping is binary_sensor.all_doors; live verification remains intentionally unaccepted.",
    ],
    deviations: [
      "The Lit implementation keeps a 66px accessible touch target, so its cards are taller than the documentation montage.",
    ],
  },
  card_binary_sensor_alert: {
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    status: "pending",
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused 320px alert comparison manually inspected against the pinned card_binary_sensor_alert reference.",
      "The real-MDI fixture preserves the unified alert variant, active accent, active-only alert badge, source icon/name options, and last-changed behavior.",
      "Picker variant exposure, variant-specific editor fields, state rendering, and all card-surface actions pass tests/default-controls-certification.test.ts.",
      "Prepared live alert mapping is binary_sensor.all_smoke_sensors; live verification remains intentionally unaccepted.",
    ],
    deviations: [
      "The active alert is represented by an MDI alert badge instead of button-card's icon_more_info_alert helper.",
      "The Lit implementation keeps a 66px accessible touch target, so its cards are taller than the documentation montage.",
    ],
  },
  card_cover: {
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    status: "pending",
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused 309px one-to-one comparison manually inspected against card_cover_controls.png.",
      "The fixture uses real MDI SVG paths and matches the source summary, device-class icon, close/stop/open row, and filled position slider.",
      "Picker defaults, graphical editor round trip, position/inversion/device-class states, favorite and tilt controls, and exact service payloads pass tests/default-controls-certification.test.ts.",
      "Prepared render-only live mapping is cover.sunscreen; no physical cover service should be operated and live remains unaccepted.",
    ],
    deviations: [
      "Upstream custom:my-slider is replaced by a dependency-free Lit range control.",
      "The implementation uses Home Assistant theme typography rather than button-card's exact text metrics.",
    ],
  },
  card_fan: {
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    status: "pending",
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused 320px on/off comparison manually inspected against card_fan_slider.png.",
      "The real-MDI fixture preserves source ordering, percentage/temperature/humidity label composition, slider fill, collapse behavior, and optional oscillation button.",
      "Picker defaults, graphical editor round trip, on/off/collapsed states, configurable service selection, and exact fan payloads pass tests/default-controls-certification.test.ts.",
      "Prepared render-only live mapping is fan.air_purifier; no physical fan service should be operated and live remains unaccepted.",
    ],
    deviations: [
      "Upstream custom:my-slider is replaced by a dependency-free Lit range control.",
      "The implementation uses a 66px accessible summary touch target rather than the compressed documentation montage density.",
    ],
  },
  card_input_boolean: {
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    status: "pending",
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused 320px on/off comparison manually inspected against the pinned card_input_boolean reference.",
      "The real-MDI fixture preserves entity icon/name, translated state, active accent, and optional active background.",
      "Picker defaults, graphical editor round trip, on/off states, and all card-surface actions pass tests/default-controls-certification.test.ts.",
      "Prepared reversible live mapping is input_boolean.dropdown_welcome; live remains unaccepted until toggle-and-restore is actually verified.",
    ],
    deviations: [
      "The Lit implementation keeps a 66px accessible touch target, so its cards are taller than the documentation montage.",
    ],
  },
  custom_card_bar_card: {
    visualAccepted: true,
    status: "pending",
    reviewerNotes: [
      "Manually inspected against the dedicated dark-theme side-by-side artifact at the upstream card width.",
      "Picker, editor, state, interaction, and live E2E stages require fresh certification.",
    ],
  },
  custom_card_afvalophaling: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    artifactPath: "docs/assets/visual-audit/custom-card-afvalophaling-batch-comparison.png",
    widths: [320],
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused 320px artifact inspected against the upstream source and the user's later semantic-row requirements.",
      "The intentionally expanded row layout preserves named waste streams, independent enablement, and date values rather than the source's compressed text summary.",
      "Full/partial rows, summary sentinel suppression, picker defaults, graphical editor controls, and outer more-info action pass local tests and Chromium evidence.",
    ],
  },
  custom_card_alarm_time: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    artifactPath: "docs/assets/visual-audit/custom-card-alarm-time-batch-comparison.png",
    widths: [440],
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "No dedicated upstream screenshot exists; the focused artifact was inspected against the pinned YAML's icon/header and minus-time-plus composition.",
      "Active, collapsed, missing/unavailable datetime, horizontal, and step-size states are covered locally.",
      "Both visible controls were clicked in Chromium and produced exact input_datetime.set_datetime payloads.",
    ],
  },
  custom_card_apexcharts: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    artifactPath: "docs/assets/visual-audit/custom-card-apexcharts-batch-comparison.png",
    widths: [640],
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Matched-width artifact inspected: three semantic legend rows, source colors, large chart field, grid lines, and three independent series are represented.",
      "The graphical editor exposes three sensor slots without unrelated generic graph fields.",
      "The source has no visible chart controls; the outer more-info action was exercised in Chromium.",
    ],
  },
  custom_card_camera: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    artifactPath: "docs/assets/visual-audit/custom-card-camera-batch-comparison.png",
    widths: [250],
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "One-to-one 250px artifact inspected: optional icon/name/label title and rounded live-image region match the source hierarchy.",
      "Title-on and image-only modes, aspect ratio, entity picture, and camera-proxy fallback are covered locally.",
      "The source has no visible controls; camera more-info was exercised through the outer card action in Chromium.",
    ],
  },
  custom_card_chromecast: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    artifactPath: "docs/assets/visual-audit/custom-card-chromecast-batch-comparison.png",
    widths: [608],
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Matched-width artifact inspected: Chromecast header and three evenly sized source-ordered controls match the upstream composition.",
      "Playing/off/unavailable icon and disabled-state behavior are covered locally.",
      "All three controls were clicked in Chromium; power/input use media_player.toggle and the center control uses media_play_pause.",
    ],
  },
  custom_card_damix48_power_details: {
    status: "pending",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: false,
    artifactPath: "docs/assets/visual-audit/custom-card-damix48-power-details-batch-comparison.png",
    widths: [385],
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "One-to-one 385px artifact inspected: flash header, period label, centered power value, and filled lower history chart follow the source hierarchy.",
      "Separate display/history entity, one/many-hour copy, chart height, and deterministic history states are covered locally.",
      "The source has no visible controls; the outer more-info action was exercised in Chromium.",
    ],
  },
  custom_card_device_tracker: {
    status: "pending",
    pickerAccepted: true, editorAccepted: true, visualAccepted: true, statesAccepted: true, interactionsAccepted: true, liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected the focused 320px dark comparison against the pinned screenshot; the phone icon, two independently positioned tracker badges, name, and translated primary state follow the source hierarchy.",
      "Home/away LAN and Bluetooth glyphs and colors were checked independently, and the outer more-info action remains the only interaction.",
      "Picker defaults, graphical editor round trip, two independent tracker slots/types, and Chromium geometry are covered locally; live Home Assistant acceptance remains false.",
    ],
  },
  custom_card_drealine_roomview: {
    status: "pending",
    pickerAccepted: true, editorAccepted: true, visualAccepted: true, statesAccepted: true, interactionsAccepted: true, liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected the focused matched-width comparison; the compact temperature/humidity header, alert strip, low-battery count, and source-ordered device row match the pinned composition.",
      "The editor and renderer use the ten named source variables rather than a generic entities array; rendered counts derive from actual group members.",
      "Sensor statuses open more-info and device controls preserve the pinned double-tap toggle behavior; live Home Assistant acceptance remains false.",
    ],
  },
  custom_card_eraycetinay_elapsed_time: {
    status: "pending",
    pickerAccepted: true, editorAccepted: true, visualAccepted: true, statesAccepted: true, interactionsAccepted: true, liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected the focused matched-width comparison; the large timer icon, name, and bold elapsed label match the pinned source crop.",
      "Date-time and time-only formatting follows the source has_date/has_time rules, including omission of minutes for date-time values.",
      "No visible control was invented; the source card's standard outer more-info action is covered locally and live acceptance remains false.",
    ],
  },
  custom_card_eraycetinay_lock: {
    status: "pending",
    pickerAccepted: true, editorAccepted: true, visualAccepted: true, statesAccepted: true, interactionsAccepted: true, liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected the focused matched-width comparison; locked/unlocked color states and the door-open and battery warning badges match the source hierarchy.",
      "Percentage and binary battery warnings, critical threshold coloring, and locked-door-open truthfulness are covered by tests.",
      "Tap defaults to more-info and optionally performs exact lock.unlock, lock.lock, or lock.open service calls; live acceptance remains false.",
    ],
  },
  custom_card_esh_room: {
    status: "pending",
    pickerAccepted: true, editorAccepted: true, visualAccepted: true, statesAccepted: true, interactionsAccepted: true, liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected the focused 320px comparison against the light-theme source; the rectangular room body, left icon/name/label hierarchy, and stacked right-side widget controls are preserved.",
      "Dedicated light, climate, and cover slots are exposed; light-plus-cover precedence matches the pinned grid while light-plus-climate is independently tested.",
      "Each visible widget emits the source toggle action for its exact entity, dynamic light color and brightness labels are truthful, and live acceptance remains false.",
    ],
  },
  custom_card_esh_welcome: {
    status: "pending",
    pickerAccepted: true, editorAccepted: true, visualAccepted: true, statesAccepted: true, interactionsAccepted: true, liveAccepted: false,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Manually inspected the focused 420px comparison; the three-control topbar, two-line greeting, and five source-colored vertical navigation pills match the pinned light-theme composition.",
      "All five pills use explicit semantic nav/icon/name/color fields rather than generic entities, and collapsed state removes the navigation row exactly as the source does.",
      "Collapse toggles its input_boolean, weather opens more-info, settings navigates to /config/dashboard, and all five pills navigate to their configured paths; live acceptance remains false.",
    ],
  },
  custom_card_heat_pump: {
    status: "accepted",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: true,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused side-by-side inspected: source hierarchy, icon controls, target-temperature stepper, and six-mode ordering are represented.",
      "The comparison now uses real @mdi/js paths, 22px glyphs, and a 475px implementation against the 488px source reference.",
      "Picker defaults, graphical editor round trip, state matrix, unsupported-mode handling, and exact control payloads pass tests/priority-certification.test.ts and tests/renderers.test.ts.",
      "All eight visible controls were clicked in Chromium; exact service payloads are recorded in docs/assets/visual-audit/priority-local-certification.json.",
      "Parent manually accepted the visual stage after reviewing the matched-width @mdi/js artifact.",
      "Authenticated Home Assistant verification passed: the card rendered and climate.set_temperature changed 23.5 to 23.0 before being restored to 23.5.",
    ],
  },
  custom_card_homeassistant_updates: {
    status: "accepted",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: true,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused side-by-side inspected: large Home Assistant hero, update badge, version hierarchy, and three source-ordered controls are represented.",
      "The comparison now uses real @mdi/js paths, a 28px hero glyph, 24px control glyphs, and matched 650px/659px widths.",
      "Picker defaults, dedicated update-entity editor fields, editor round trip, available/clear/unavailable states, and event isolation pass local tests.",
      "All three visible controls were clicked in Chromium; exact action payloads are recorded in docs/assets/visual-audit/priority-local-certification.json.",
      "Parent manually accepted the visual stage after reviewing the matched-width @mdi/js artifact.",
      "Authenticated Home Assistant verification passed: release notes opened the exact 2026.9.3 URL, settings navigated to /config/updates, and update opened entity more-info.",
    ],
  },
  custom_card_nik_nas: {
    status: "accepted",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: true,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused side-by-side inspected after correcting SVG namespace rendering: two bordered tiles, three semantic metrics, and three utilization rings are visible.",
      "The refreshed comparison uses real 24px MDI glyphs and measures 510x360 against the 512x360 source reference.",
      "Parent manually accepted the refreshed visual stage after reviewing the geometry-matched source comparison.",
      "Picker semantic defaults, status plus four metric editor slots, chart settings, editor round trip, online/off/unavailable collapse states, and configured ring maxima pass local tests.",
      "The status tile and outer card surface were clicked in Chromium; exact more-info evidence is recorded in docs/assets/visual-audit/priority-local-certification.json.",
      "Authenticated Home Assistant verification passed at 330x266: clientWidth and scrollWidth were both 330, both top tiles and the 132px rings were fully visible, and the status tile opened switch.nas_plug more-info.",
    ],
  },
  custom_card_nik_tablet: {
    status: "accepted",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: true,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused side-by-side inspected: source-ordered six-button grid, RAM/Disk/Power row, battery summary, and thick progress bar are represented.",
      "The comparison now uses exact MDI paths, 22px glyphs, source-like active colors, and matched 390px/396px widths.",
      "Picker semantic defaults, graphical editor round trip, active/inactive/unavailable state matrix, and exact six-control service payloads pass local tests.",
      "All six visible controls were clicked in Chromium; exact service payloads are recorded in docs/assets/visual-audit/priority-local-certification.json.",
      "Parent manually accepted the visual stage after reviewing the matched-width @mdi/js artifact.",
      "Authenticated Home Assistant verification passed at 330px: omitted RAM/Disk slots produced no placeholder text, configured unavailable controls rendered disabled, and the outer action opened device_tracker.bram_tablet_2 more-info.",
    ],
  },
  custom_card_person_info: {
    status: "accepted",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: true,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused side-by-side inspected: full variant now uses avatar/location hierarchy with zone/driving badge and separate battery/commute details.",
      "The refreshed one-to-one comparison measures 165x105 for both the cropped source card and dark-theme implementation.",
      "Parent manually accepted the refreshed visual stage after reviewing the one-to-one dark tile comparison.",
      "Picker variant exposure, full editor round trip, address/locality/multiline/zone/driving/charging/threshold/commute states, and configured actions pass local tests.",
      "Tap and configured hold were exercised in Chromium; exact action targets are recorded in docs/assets/visual-audit/priority-local-certification.json.",
      "Authenticated Home Assistant verification passed: tap opened person.joris and hold targeted sensor.joris_mobile_battery_level.",
    ],
  },
  custom_card_person_info_small: {
    status: "accepted",
    pickerAccepted: true,
    editorAccepted: true,
    visualAccepted: true,
    statesAccepted: true,
    interactionsAccepted: true,
    liveAccepted: true,
    inspectedAt: "2026-09-23",
    reviewerNotes: [
      "Focused side-by-side inspected: compact variant is one person per card with avatar badge, battery circle, centered name, and location label.",
      "The reference is cropped to one 155px source tile and compared with one 155px implementation tile.",
      "Picker variant exposure, graphical editor round trip, home/driving/zone/charging/battery-threshold states, and default tap/hold targeting pass local tests.",
      "Tap and hold were exercised in Chromium; payload evidence is recorded in docs/assets/visual-audit/priority-local-certification.json.",
      "Parent manually accepted the visual stage after reviewing the one-to-one source tile comparison.",
      "Authenticated Home Assistant verification passed at 330x118 with tap and hold targeting the configured person and battery entities.",
    ],
  },
};

export const VISUAL_AUDIT: readonly VisualAuditEntry[] = UPSTREAM_CATALOG.map((source) => {
  const item = publicItemForSource(source.upstreamId);
  if (!item) throw new Error(`${source.upstreamId} has no public card mapping.`);
  if (source.category !== "default-card" && source.category !== "custom-card") {
    throw new Error(`${source.upstreamId} is not a card source.`);
  }
  const variant = variantForSource(source.upstreamId);
  const baseline: VisualAuditEntry = {
    sourceId: source.upstreamId,
    publicId: item.upstreamId,
    variant,
    category: source.category,
    rendererId: item.upstreamId,
    compositionId: `${item.upstreamId}${variant ? `:${variant}` : ""}`,
    sourcePath: source.sourcePath,
    fixturePath: "demo/index.html",
    fixtureId: source.upstreamId,
    themes: ["light", "dark"],
    widths: [237, 360],
    requiredRegions: [],
    forbiddenRegions: [],
    status: "pending",
    pickerAccepted: false,
    editorAccepted: false,
    visualAccepted: false,
    statesAccepted: false,
    interactionsAccepted: false,
    liveAccepted: false,
    reviewerNotes: [
      "Previous batch-generated comparison was not accepted as manual visual or interaction review.",
    ],
    deviations: [],
  };
  const reviewed = manuallyReviewed[source.upstreamId];
  return {
    ...baseline,
    ...accepted[source.upstreamId],
    status: reviewed?.status ?? "pending",
    pickerAccepted: reviewed?.pickerAccepted ?? false,
    editorAccepted: reviewed?.editorAccepted ?? false,
    visualAccepted: reviewed?.visualAccepted ?? false,
    statesAccepted: reviewed?.statesAccepted ?? false,
    interactionsAccepted: reviewed?.interactionsAccepted ?? false,
    liveAccepted: reviewed?.liveAccepted ?? false,
    reviewerNotes: reviewed?.reviewerNotes ?? baseline.reviewerNotes,
    inspectedAt: reviewed?.inspectedAt,
    deviations: reviewed?.deviations ?? accepted[source.upstreamId]?.deviations ?? baseline.deviations,
  };
});

export const visualAuditProgress = (): {
  accepted: number;
  pickerAccepted: number;
  editorAccepted: number;
  visualAccepted: number;
  statesAccepted: number;
  interactionsAccepted: number;
  liveAccepted: number;
  total: number;
} => ({
  accepted: VISUAL_AUDIT.filter((entry) =>
    entry.pickerAccepted &&
    entry.editorAccepted &&
    entry.visualAccepted &&
    entry.statesAccepted &&
    entry.interactionsAccepted &&
    entry.liveAccepted).length,
  pickerAccepted: VISUAL_AUDIT.filter((entry) => entry.pickerAccepted).length,
  editorAccepted: VISUAL_AUDIT.filter((entry) => entry.editorAccepted).length,
  visualAccepted: VISUAL_AUDIT.filter((entry) => entry.visualAccepted).length,
  statesAccepted: VISUAL_AUDIT.filter((entry) => entry.statesAccepted).length,
  interactionsAccepted: VISUAL_AUDIT.filter((entry) => entry.interactionsAccepted).length,
  liveAccepted: VISUAL_AUDIT.filter((entry) => entry.liveAccepted).length,
  total: VISUAL_AUDIT.length,
});
